### ISSUE TITLE
console.error blowing up layout

### ISSUE THREAD

**Issue by arb** [FormidableLabs/webpack-dashboard#10]
There are things currently in my build that use `console.error` to log information out to `stderr`. This causes a lot of unexpected text to be flushed to the output container and renders the rest of the view un-readable. 

Would it be possible to make that container scrollable? The webpack loader responsible doesn't expose an option to make it hush about CSS warnings or errors.

I've also opened a corresponding issue to see if I can suppress the warnings from upstream as well.

**Comment by kenwheeler** [comment]
What steps are you taking to silence errors right now?

**Comment by kenwheeler** [comment]
can you try adding `new webpack.NoErrorsPlugin()`?

**Comment by kenwheeler** [comment]
I'm going to close this and continue in #12
