### ISSUE TITLE
can't run binary

### ISSUE THREAD

**Issue by brandonmp** [FormidableLabs/webpack-dashboard#100]
[omitting boilerplate details as not rly applicable to this question]

This feels like a newb question: where is the binary `webpack-dashboard`? 

I get `command not found` when running from terminal, and when trying to append to `$PATH` via `~/.profile`, I'm not sure where to point, as I can't find a binary in the `node_modules/webpack-dashboard` folder.

this poses a problem b/c the `command not found` also stops the `npm script` in its tracks

###### More Details

- What operating system are you on? **Ubuntu 16.04**
- What terminal application are you using? **bash 4.3.46(1)**
- What version of webpack-dashboard are you using?  **0.1.8**
- What is the output of running `echo $TERM`?  **xterm-256color**

**Comment by DanielMcAssey** [comment]
The Binary should be in node_modules/.bin/

**Comment by brandonmp** [comment]
thanks, that did the trick
