### ISSUE TITLE
Feature: A minimal bar mode (a thin bar when resized)

### ISSUE THREAD

**Issue by lakhman** [FormidableLabs/webpack-dashboard#105]
On terminal resizing, when only a few lines are able to be displayed, it should show a "minimal" bar instead, as nothing is legible when you can only see 3 lines.

Perhaps something like:

[LOG MESSAGE]  [STATUS] [OPERATION][PROGRESS]

So when the screen resizes, check if a minimum amount of lines are visible and change the theme accordingly.

A "flight mode" if you will - as "minimal" is already taken, is it really "minimal" - not really, a minimal bar like this makes more sense and would be so useful when in editors.

====================================================================

# Jetbrains editor example:

When only 4-6 lines are visible, it's useless, could we turn it into a minimal bar showing the basic compilation info (status, progress, last log message).

![image](http://i.imgur.com/dFoKnev.gif)

I also agree with this request, less spacing between the table rows would be nice:

https://github.com/FormidableLabs/webpack-dashboard/issues/92

**Comment by kenwheeler** [comment]
Have you tried minimal mode?

**Comment by lakhman** [comment]
Yeah I did, it got rid of the assets and bundle boxes (If I remember correctly) and moved the other 3 boxes below, this didn't help, I had a play around with the blessed box in the source to see if I could "theme" it, I could but making a minimal bar like this was beyond my scope. Sorry, didn't mean to moan, was just an idea! I was hoping I could hook in my own theme somehow but this didn't seem easily doable.

Although I did learn you can also attach click behaviour on the boxes! Maybe we could show the dev server address and asset list (I forget the url) at the top and on click they could simply click it to 'open "<url>"' in the users default browser. (and any other details you webpack experts are aware off)

Blessed is awesome! This plugin is a great example of its use! I think I might be making some NASA dashboards myself! Haha! 
seriously, just simple things like:

- viewing existing installed packages (global, local for node, python)
- current location of common tools (brew, Python, Java, Php, Apache, etc) and configuration files
- npmjs search **(in your terminal)**
- GitHub trending **(in your terminal)**

so many possibilities! blessed really makes this quite easy todo! If anyone implements the above let me know via a comment else maybe I'll take it up when I get some time!

Thanks!

**Comment by lakhman** [comment]
I kind of got it working with something like this:

``` js
// Inside Dashboard()
this.collapseBarLineCount = options && options.collapseBarLineCount || 10;

// Inside this.modules (this works fine)
var self = this;

this.modules.on("resize", function() {
    if (this.screen.height < self.collapseBarLineCount && !this.minimal) {
        this.hide();
    } else {
        this.show();
    }
});
```

When the screen has less than 10 lines, it hides the modules (and assets - not shown here) boxes, and shows them again once larger.

This works, but now I want to change the height of the `log` box so it's full height (because the modules and assets are hidden).

```js
// Inside `layoutLog`
var self = this;
this.log.on("resize", function() {
    // This doesn't work?
    this.height = '100%';
    // if (this.screen.height < self.collapseBarLineCount && !this.minimal) {
    //     this.options.style.height = '100%';
    // } else {
    //     this.options.height = this.minimal ? "70%" : "42%";
    // }
});
```

## Q: How can I dynamically change the height of the log box?  
(The above snippet doesn't work)

Manually overriding the `height` option works and I see a nice small clean log (Screenshot).

I also have to remove the `output.push('')` in `format-output.js`.

This kind of gives me what I'm after (but the height is hardcoded - How can I change that dynamically?).

![image](https://cloud.githubusercontent.com/assets/1582690/18013298/54fdd7ea-6bb5-11e6-9e92-d9fe2e11d2d5.png)


This libraries quite easy to get your head around, it's no where near as complicated as I would've thought, very easy to tinker with. I'll make a pull request once I solve this last height issue and format it better (I also want to show the progress bar and other info if I can squeeze it in).

**Comment by kenwheeler** [comment]
closing, webview will fix this
