### ISSUE TITLE
Transfer ownership of repository to NASA

### ISSUE THREAD

**Issue by sbussard** [FormidableLabs/webpack-dashboard#106]
As mentioned in the `README.md` file, using this dashboard is basically like working for NASA. 
Why not make it official by transferring ownership of this repository to @nasa? 👾 

Having worked for NASA in the past, I can vouch for their awesomeness.

**Comment by kenwheeler** [comment]
I think @nasa has a way better open source dashboard than I do https://github.com/nasa/openmct
