### ISSUE TITLE
Won't Start: Port in Use

### ISSUE THREAD

**Issue by jonstuebe** [FormidableLabs/webpack-dashboard#107]
Webpack seems to be holding on to the port and not killing it once I quit webpack-dashboard.

[Screenshot](https://www.dropbox.com/s/ie1ruz4pjuwc4tn/Screenshot%202016-08-26%2011.16.09.png?dl=0)
# 
#### Reproduction Steps

Step 1: run webpack dashboard via iterm
Step 2: stop using ctrl+c
Step 3: re open webpack dashboard via iterm
# 
###### webpack.config.js

```
...
const DashboardPlugin = require('webpack-dashboard/plugin');
...
let plugins = [];
...
if (IS_DEV) {
   plugins.push(new DashboardPlugin());
}
...
```
# 
#### More Details

OS: El Capitan v 10.11.6
webpack-dashboard v 0.1.8

**Comment by kenwheeler** [comment]
can I see your package.json?

**Comment by mwq27** [comment]
Has anyone been able to look into this issue?  I'm having the same problem, using
```
"webpack": "^2.2.0-rc.2",
"webpack-dashboard": "^0.2.0",
```

**Comment by KarandikarMihir** [comment]
I can confirm this.

**Comment by KarandikarMihir** [comment]
I can confirm this :( Sadly I have to drop dashboard in our project until this is fixed.

**Comment by kenwheeler** [comment]
@KarandikarMihir is your port in use?

**Comment by kenwheeler** [comment]
Has anyone here tried using custom ports? You can set a custom one like:

```
new DashboardPlugin({ port: 123444 })
```

and then

```
webpack-dashboard -p 123444 -- node index.js
```

**Comment by KarandikarMihir** [comment]
@kenwheeler First of all, thanks for this super-cool dashboard. I loved it. 

I tried `new DashboardPlugin({ port: 123444 })`, but no joy. I _think_ I've tried the second option as well. But let me confirm once again. 

That being said, why does the dashboard not find a free port automatically? Is that possible?

**Comment by ryan-roemer** [comment]
@jonstuebe / others -- Is this still an issue in latest `webpack-dashboard`? If not, can someone get me an updated reproduction of the problem ideally via a GitHub repo + documented steps to cause the problem so I can hack on it.

My best guess is that a hard OS signal is orphaning processes or something. If that's the case, we can probably put an OS signal listener to try a last-ditch process tree kill or something...

@KarandikarMihir -- 

> That being said, why does the dashboard not find a free port automatically? Is that possible?

Yes, and there are libraries to do that, but IIRC all of them shell out to the operating system to literally ping ports until they find one open.

W

**Comment by KarandikarMihir** [comment]
@ryan-roemer Okay.. I'm not sure if I can pull it off, but I can give it a try. It'd be a nice-to-have for the dashboard.

**Comment by ryan-roemer** [comment]
This _may_ be related to the inspectpack daemon creation which we've tweaked in `1.0.1`. Can folks experiencing the problem upgrade to `^1.0.1` and report back here?

If still a problem, can someone create a minimal repository with install + reproduction steps so we can dive in more quickly to see what's up? Thanks!

**Comment by ryan-roemer** [comment]
Closing as there are no updated reports or reproductions for us to work with. If the issue persists in `webpack-dashboard@latest`, please create a minimal repository with install + reproduction steps to properly diagnose what's going on. Thanks!
