### ISSUE TITLE
Don't include modules that are part of the dev dependencies.

### ISSUE THREAD

**Issue by AriaFallah** [FormidableLabs/webpack-dashboard#11]
Awesome project! Makes webpack look not nearly as lame, but I do have one question.

Not sure if this is possible, but `sockjs-client` (a webpack-dev server dependency) is sitting at the top of the list of modules along with a bunch of other random dev dependencies. Is there any way you could update the `modules` display such that it only shows the packages in the "dependencies" field of your `package.json` instead of all packages?

<img width="1440" alt="screen shot 2016-08-15 at 12 20 51 pm" src="https://cloud.githubusercontent.com/assets/9424976/17671028/bb87323a-62e2-11e6-933d-2c3452185536.png">

Of the modules in this screenshot, I'm only using `lie`, and `fecha`. The rest is noise.

**Comment by kenwheeler** [comment]
I _should_ be able to. I"ll look into it.

**Comment by AriaFallah** [comment]
@kenwheeler appreciate it!

**Comment by ryan-roemer** [comment]
This should be fixed in webpack-dashboard^2. If you find that it persists in current form, then if you could open up a new issue with a minimal repository with install + error reproduction steps to see the issue, we'll dig in!
