### ISSUE TITLE
hot reload doesn't seems to be working with dashboard

### ISSUE THREAD

**Issue by rajanand02** [FormidableLabs/webpack-dashboard#110]
>  i have this following command in my npm start script
> `webpack-dashboard -p 3001 webpack-dev-server --progress --inline --hot`

without webpack-dashboard the webpack-dev-server is able to work with hot module replacement but if I enable webpack-dashboard hot is not working.
###### Please provide a gist of relevant files
1. package.json -> https://gist.github.com/rajanand02/87ca096e1fa885c52c714d38be3bece5
2. webpack.config.js -> https://gist.github.com/rajanand02/cf08ee46cb9a420dfabca83aab426cab#file-webpack-config-js-L92
# 
###### More Details
- What operating system are you on?
  `Linux Mint 17`
- What terminal application are you using?
  `terminator with tmux`
- What version of webpack-dashboard are you using?
  `0.1.8`
- What is the output of running `echo $TERM`?
  `screen-256color`

**Comment by milushov** [comment]
@rajanand02 rajanand02, can you try setup your config like this?

I have the following config and it works fine with hot reload.
```
var HtmlWebpackPlugin = require('html-webpack-plugin');
var ComponentResolverPlugin = require('component-resolver-webpack');
var OpenBrowserPlugin = require('open-browser-webpack-plugin');

...

 plugins: plugins.concat([
    ...
    new OpenBrowserPlugin({url: `http://${HOST}:${PORT}`})
  ])
```

**Comment by rajanand02** [comment]
@milushov I have tried adding as you suggested but the result is still the same. Moreover I had to pass the port to DashboardPlugin. Without port It wasn't showing `modules, assets etc`

**Comment by kenwheeler** [comment]
are you getting an error, or it just doesn't work?

**Comment by rajanand02** [comment]
@kenwheeler I am not getting any error. The webpack is working fine but only hot reload is not working.

**Comment by adityasaxena** [comment]
hot reload is not working for me, either. could someone provide a solution, please?

**Comment by f0rr0** [comment]
Can confirm it's working with webpack 2. Make sure port in entry matches the port your server is running at:

```js
entry: [
    'webpack-dev-server/client?http://localhost:8080',
    'webpack/hot/dev-server',
    './index.jsx'
  ]
```

**Comment by joefraley** [comment]
@f0rr0 do you mean this?

```javascript
$ webpack-dashboard -p 3001 -- webpack-dev-server --config webpack.config.js

// webpack.config.js
...
entry: [
    'webpack-dev-server/client?http://localhost:3001', <----- same as -p above
    'webpack/hot/dev-server',
    './index.jsx'
  ]
```

I get:
```
Error: listen EADDRINUSE 0.0.0.0:3001
```

**Comment by ryan-roemer** [comment]
@rajanand02 -- Can you upgrade to `^1.0.1` and try again?

If the issue persists, can you create a minimal repository with install + reproduction steps so that we can jump in and more quickly figure out what's going on?

**Comment by ryan-roemer** [comment]
Closing as there are no updated reports or reproductions for us to work with. If the issue persists in `webpack-dashboard@latest`, please create a minimal repository with install + reproduction steps to properly diagnose what's going on. Thanks!
