### ISSUE TITLE
Build slows as a function of window size

### ISSUE THREAD

**Issue by texel** [FormidableLabs/webpack-dashboard#111]
> Please provide a description of the bug / issue, and provide the details below:

It seems that the bigger my terminal window, the slower the build (or maybe the smaller the window, the faster the build?)

Here's a screenshot of my project building with a tiny window (9.2sec build time):

![tiny window](https://texel-monosnap.s3.amazonaws.com/1._webpack-dashboard_node_2016-09-03_00-22-28.png)

And here it is with a large one (27 sec build time):

![large window](https://texel-monosnap.s3.amazonaws.com/1._webpack-dashboard_node_2016-09-03_00-19-17.png)
# 
###### Steps to reproduce the problem

Pick a project and embiggen your window, then build.
# 
###### More Details

I'm using webpack-dev-server with the webpack-dashboard plugin.
- What operating system are you on? 
  Mac OS X 10.11.6
- What terminal application are you using? 
  iTerm2 3.0.8 (But I've confirmed the issue on Terminal as well)
- What version of webpack-dashboard are you using? 
  0.1.8
- What is the output of running `echo $TERM`?
  xterm-256color (I'm running zsh but I've also confirmed on bash)

**Comment by kenwheeler** [comment]
whoah, thats odd. which setup strategy are you using?

**Comment by texel** [comment]
@kenwheeler sorry for the delay. I'm using the plugin communicating to webpack-dev-server over a socket.

**Comment by kenwheeler** [comment]
This should be resolved now that they are decoupled
