### ISSUE TITLE
dashboard output problem

### ISSUE THREAD

**Issue by majianxiong** [FormidableLabs/webpack-dashboard#112]
> Please provide a description of the bug / issue, and provide the details below:

====================================================================

######  Output problem

![image](https://cloud.githubusercontent.com/assets/887531/18236349/b35eecbc-7357-11e6-8a7e-6c76b6c4fb39.png)

====================================================================

###### More Details
- The line into letters?

**Comment by falconxunit** [comment]
dashboard

Martin Leclerc

**Comment by majianxiong** [comment]
@falconxunit Is not very understanding

**Comment by kenwheeler** [comment]
closing, continuing discussion in #85
