### ISSUE TITLE
Doesn't work on w8.1. Displaying on  node screen

### ISSUE THREAD

**Issue by mesutyigit** [FormidableLabs/webpack-dashboard#113]
package.json scripts -> 
"start_mesut2":"webpack-dashboard --  webpack-dev-server --history-api-fallback --config conf/webpack.config.mesut.js --port 8081 --host 0.0.0.0 --hot --progress --colors --content-base ./build"

npm run start_mesut2

opening node console and contiuning from here

![image](https://cloud.githubusercontent.com/assets/11429147/18263530/611e9850-7413-11e6-9e94-b24bd919d6a6.png)

**Comment by kenwheeler** [comment]
what does your config look like?
