### ISSUE TITLE
Jenkins error

### ISSUE THREAD

**Issue by albertolive** [FormidableLabs/webpack-dashboard#115]
Hi,

I have installed this great tool but when I try to deploy my project with jenkins, the task freezes for ever.

Anyone knows why it happens?

Jenkins ver. 1.658

Thanks

**Comment by miguelbermudez** [comment]
@albertolive had the same issue. The process hung and jenkins couldn't complete building. The solution I came up with is, only initialize the plugin in dev mode. Disable it for production.  
Jenkins ver. 1.609.2.

**Comment by kenwheeler** [comment]
I would need more information to accurately debug this.  Will reopen when issue_template is followed.
