### ISSUE TITLE
Package is broken

### ISSUE THREAD

**Issue by milushov** [FormidableLabs/webpack-dashboard#119]
Npm package seems to be broken because code in the repo is different oO

![image](https://cloud.githubusercontent.com/assets/424326/18753840/3ede126e-80ef-11e6-8803-43d7232c7221.png)

If not so what I'm doing wrong?

```
rm -rf node_modules/webpack-dashboard
npm install --save-dev webpack-dashboard
cat node_modules/webpack-dashboard/dashboard/index.js | head -15 | tail -10
cat node_modules/webpack-dashboard/package.json | grep version
```

**Comment by milushov** [comment]
arr it's old issue https://github.com/FormidableLabs/webpack-dashboard/pull/101#issuecomment-244533094

@kenwheeler hey, bump the package please

**Comment by Nizam-Ahamed** [comment]
notifications@github.com

**Comment by exogen** [comment]
@milushov Should be in `0.2.0` now!
