### ISSUE TITLE
Alternate Renderer

### ISSUE THREAD

**Issue by kenwheeler** [FormidableLabs/webpack-dashboard#120]
After careful consideration, I've decided I should probably offer a non terminal renderer as well, especially due to issues faced by windows users. Still working out what form it should take, so feedback here would be super welcome

Press the corresponding reaction for your vote
1. Web view (Smiley)
2. Electron view (Confetti)
3. Chrome plugin (Heart)

**Comment by cristian-sima** [comment]
Any progress on this?

Is something on which you are working and you're keeping it private until finished or there is no project  started. 

I'm asking because I want to start a project like this, otherwise I may contribute to something similar.

**Comment by Nizam-Ahamed** [comment]
nntahamed@gmail.com

**Comment by cristian-sima** [comment]
Should I email that or what? I don't quite understand

**Comment by kenwheeler** [comment]
Its coming. Building it with a yet to be released Formidable project, so it's in private for the time being.

**Comment by ForsakenHarmony** [comment]
aww :/

**Comment by cristian-sima** [comment]
Still private?

**Comment by kenwheeler** [comment]
Nope its here https://github.com/FormidableLabs/electron-webpack-dashboard
