### ISSUE TITLE
only log worked

### ISSUE THREAD

**Issue by shengxinjing** [FormidableLabs/webpack-dashboard#121]
> Please provide a description of the bug / issue, and provide the details below:
# 
###### If the issue is visual, please provide screenshots here

![dash-not-working](https://cloud.githubusercontent.com/assets/1905176/18784523/431e434a-81c5-11e6-8319-94cad36aa8d1.png)

```
/**
 * Created by sheng on 16/7/14.
 */
'use strict'
var webpack = require('webpack')
var HtmlWebpackPlugin = require('html-webpack-plugin')
var ExtractTextPlugin = require('extract-text-webpack-plugin')
var DashboardPlugin = require('webpack-dashboard/plugin')
var Dashboard = require('webpack-dashboard');
var dashboard = new Dashboard();
var path = require('path')

var config = {
  entry: __dirname + '/src/app.js',
  output: {
    path: 'dist',
    // filename: 'bundle.js'
    filename: 'bundle.[hash].js'
  },
  resolve: {
    modulesDirectories: ['node_modules', './'],
    alias: {
      'npm': __dirname + '/node_modules'

    },
    extensions: ['', '.js', '.html', '.css', '.styl']
  },
  module: {
    loaders: [{
      test: /\.js$/,
      loaders: ['ng-annotate?add=true', 'babel'],
      exclude: /node_modules/
    }, {
      test: /\.html$/,
      loader: 'html'
    }, {
      test: /\.css$/,
      loader: ExtractTextPlugin.extract("style-loader","css-loader")
    }, {
      test: /\.jade$/,
      loader: "pug-html-loader"
    }, {
      test: /\.(png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot)$/,
      loader: 'file'
    }, {
      test: /\.styl$/,
      loader: ExtractTextPlugin.extract(
        'style-loader',
        'css-loader?sourceMap!stylus?sourceMap'
      )
    }]
  },
  plugins: [
    // new ExtractTextPlugin("[name].css"),
    new DashboardPlugin(dashboard.setData),
    new webpack.BannerPlugin("Copyright addnewer inc."),
    new ExtractTextPlugin("styles.css"),
    new HtmlWebpackPlugin({
      title: 'Custom template using Handlebars',
      template: 'src/index.jade',
      inject: 'body'
    }),
    new webpack.DefinePlugin({
      DEV: true,
      RAP: false
    })
  ],


  devtool: 'eval-source-map',

  //   devtool:false,
  devServer: {
    port: 3000,
    contentBase: __dirname,
    colors: true,
    hot: true,
    proxy: {
      '/rap/*': {
        target: 'http://192.168.0.30/mockjsdata/5',
        rewrite: function(req) {
          req.url = req.url.replace(/^\/rap/, '')
          console.log(req.url)
        },
        changeOrigin: true,
        secure: false
      },
      '/dev/*': {
        target: 'http://dev.tmcms.com',
        rewrite: function(req, res) {
          req.url = req.url.replace(/^\/dev/, '')
          console.log(res)
        },
        changeOrigin: true,
        secure: false
      }
    }
  }
}
module.exports = config

```
# 
###### Steps to reproduce the problem
# 
###### Please provide a gist of relevant files
1. package.json (specifically the script you are using to start the dashboard)
2. webpack.config.js
3. index.js (Your express based dev server, if applicable)
# 
###### More Details
- What operating system are you on?
- What terminal application are you using?
- What version of webpack-dashboard are you using?
- What is the output of running `echo $TERM`?

**Comment by shengxinjing** [comment]
npm script:
`    "dev:board": " webpack-dashboard webpack-dev-server --profile --inline --hot --watch --colors --progress --display-error-details",
`

**Comment by lukefx** [comment]
Same here, tried with several projects, only log works with latest webpack.

**Comment by Nizam-Ahamed** [comment]
webpack-dashboard@noreply.github.com

**Comment by kenwheeler** [comment]
Have you tried using bin based approach?

**Comment by lukefx** [comment]
Yepp...same result

Am Donnerstag, 29. September 2016 schrieb Ken Wheeler :

**Comment by kenwheeler** [comment]
when you say latest webpack, which webpack is that?

**Comment by asilaghi** [comment]
I too see the same issue, running like this: 
`"scripts": {
    "build": "webpack",
    "start": "webpack-dashboard -m -- webpack-dev-server"
  },`

using webpack 1.13.2, webpack-dashboard 0.2.0, webpack-dev-server 1.16.2 on macOS Sierra

**Comment by mwq27** [comment]
I have this same problem, using Webpack 2 and wp dashboard 0.2.0 and wp dev server 2.2.0-rc.0

**Comment by mwq27** [comment]
I saw someone else advise in a different issue that if you are already calling ```webpack-dashboard``` in your package.json, you don't need to do `new Dashboard()` in your webpack.config, or pass `dashboard.setData` to the plugin.  So your webpack.config should just look like 
```js
plugins: [
    new DashboardPlugin(),
...
```
and your package.json like
```js
"scripts": {
    "start": "webpack-dashboard -c magenta -- webpack-dev-server --config ./config/webpack.config.dev.js",
```

This fixed the problem for me.

**Comment by pgib** [comment]
I moved the DashboardPlugin to the end of the plugins list, and that resolved the issue for me. Some documentation about placement in the `plugins: []` would be good.

**Comment by josephrexme** [comment]
Any ideas how this can be solved for an express server when using
```js
compiler.apply(new DashboardPlugin());
```
Couldn't find an issue specifically for that but since this is related thought it's not worth creating a new issue for @kenwheeler

**Comment by josephrexme** [comment]
So I added the plugin to my webpack.config.js and it started showing those fields. Weird I thought since I had it in my express server file I didn't need it there. But now it says `Could not load module assets sizes`. Server runs and now I see status and progress but Module and Assets panes are still empty with the error
