### ISSUE TITLE
not working with Procfile apps

### ISSUE THREAD

**Issue by alfredoreduarte** [FormidableLabs/webpack-dashboard#122]
Hi! I really love this tool, but I need to run my apps locally as Procfile apps (with `heroku local`) in order to read from the `.env` file. This doesn't seem to play nice with either webpack-dashboard or zsh. This is what I get:

![screen shot 2016-09-25 at 9 42 44 pm](https://cloud.githubusercontent.com/assets/4633753/18820204/8d474b10-8369-11e6-8c43-9ca00fff5981.png)

Basically, this is the relevant line from my package.json. Nothing weird:

`"start": "NODE_ENV=development webpack-dashboard -c magenta -- nodemon server.js",`

And my Procfile:

`web: npm start`

Has any of you run on this problem as well?

**Comment by kenwheeler** [comment]
Yeah this must be because proc is running it. Closing because I'm not sure how to fix this, and I'll be adding a web interface soon that will provide an alternate method.
