### ISSUE TITLE
format-modules.js doesn't run on early versions of NPM/node.

### ISSUE THREAD

**Issue by casperOne** [FormidableLabs/webpack-dashboard#126]
node/npm versions:

node: 0.12.2
npm: 2.7.4

I know that these are ancient versions of node (it's what's installed with VS.NET 2015 by default).

That said, there's only a single line that needs to be changed in order to have the dashboard run on this version (line 142 in format-modules.js).

Old:

`          packageVersion,`

It's using inference to determine the property name in the object.  Simply changing it to:

`          packageVersion: packageVersion,`

Allows it to run. I've made this change locally, and it runs now (great work, thanks!).

That said, I hate the idea of this local change in a module obtained through npm.  Any chance this can be integrated into the next release?

**Comment by kenwheeler** [comment]
ahhh nice catch. care to PR?

**Comment by phra** [comment]
i'm preparing now a PR. @kenwheeler

**Comment by phra** [comment]
here we go. https://github.com/FormidableLabs/webpack-dashboard/pull/128

**Comment by phra** [comment]
@kenwheeler  you should publish a patch release in order to ship the fix to the mainstream.

**Comment by mdopieralski** [comment]
Yup, this fix is not avaible while installing via npm (unless you use npm to install from github).
