### ISSUE TITLE
Wrapping hjs-webpack dev server?

### ISSUE THREAD

**Issue by tdd** [FormidableLabs/webpack-dashboard#127]
Hey there,

This project looks downright awesome, however I don't get much of the promised features when trying to use it over my webpack dev server setup of choice, which is [hjs-webpack](https://github.com/HenrikJoreteg/hjs-webpack).

It basically automates most of the plugin and config setup (it acts as a factory of sorts for the config) and I run it through its own dev server wrapper, `hjs-dev-server`, which sits on top of `webpack-dev-middleware` and `webpack-hot-middleware`.

All I get is the log in the top-left panel, with no particular syntax highlighting or auto-focus on syntax errors, etc. Nothing in any of the other panels (see attached screenshot)

====================================================================

###### Screenshots

![My dashboard instantiation, showing precious little](https://cloud.githubusercontent.com/assets/3752/19184715/b31475ac-8c7e-11e6-94a1-37a0e2c5ec47.png)

====================================================================

###### Steps to reproduce the problem

1. Try using it on [my public front-end training repo](https://github.com/deliciousinsights/goal-tracker/tree/webpack-dashboard) (I linked to my experimental `webpack-dashboard` branch here)
2. `npm i` and `npm start`

- I've tried putting the plugin in various positions (first or last in the plugins, for instance), to no avail.
- The `start` npm script just prefixes my traditional `hjs-dev-server` call with `webpack-dashboard -- `, as per the "new use" docs.

====================================================================

###### Please provide a gist of relevant files

Everything is in the repo branch linked above

====================================================================

###### More Details

- OS: OSX El Capitan 10.11.5
- Terminal: OSX's built-in Terminal app, with mouse reporting enabled.
- Dashboard version: 0.2.0 (default install from npm just now)
- `$TERM`:  `xterm-256color`

Looking forward to making this work, it looks amazing and I'd love to bring that in my training!

**Comment by kenwheeler** [comment]
HI @tdd!

It looks like in your webpack.config you are setting `port` to 3002. To get to this work, I'd suggest adding `-p 3002` to your start script.

So in package.json, your start would instead read `"start": "webpack-dashboard -p 3002 -- hjs-dev-server",`

**Comment by kenwheeler** [comment]
Let me know if this sorts it out for you.

**Comment by tdd** [comment]
Woah, ashamed I didn't pick up on that. Works great, thanks a ton! :+1:


On Sun, Oct 9, 2016, at 20:30, Ken Wheeler wrote:
> Let me know if this sorts it out for you.
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].
>

--
Christophe Porteneuve
tdd@tddsworld.com

Links:

  1. https://github.com/FormidableLabs/webpack-dashboard/issues/127#issuecomment-252503497

**Comment by kenwheeler** [comment]
awesome!

**Comment by falconxunit** [comment]
Thanks

  Also if you need more question, let me know.

  Sincerely

          Martin Leclerc
