### ISSUE TITLE
Can add an option for disable webpack-dashboard?

### ISSUE THREAD

**Issue by zhongzhi107** [FormidableLabs/webpack-dashboard#129]
webpack-dashboard is a very good tool. Sometimes, for some reason need to temporarily disable it, can add a disabled parameters for webpack-dashboard, such as -d or --disable

```sh
# disabled webpack-dashboard, like `node index.js`
webpack-dashboard -d -- node index.js

**Comment by kenwheeler** [comment]
if you'd have a task where you'd add a `-d` why not just remove the `webpack-dashboard` part instead?

**Comment by zhongzhi107** [comment]
Yes, it can, thanks for the reply.

**Comment by falconxunit** [comment]
Can i aplly

**Comment by pribilinskiy** [comment]
@kenwheeler in my case I can't remove `webpack-dashboard` from command-line as it is added in a `configl.yml` file of a Symfony Bundle that Integrate Webpack into Symfony (a well-known PHP framework).
 
See `dev_server.tty_prefix` in the docs https://github.com/mariusbalcytis/webpack-bundle#configuration

To toggle `webpack-dashboard` the whole tty_prefix section should be changed:
```
            tty_prefix:
                - node
                - node_modules/webpack-dashboard/bin/webpack-dashboard.js
                - "--"
```
should be changed to 
```
            tty_prefix: []
```

If there would be a `disable` argument we could toggle with a custom user-specific parameter (that can be changed by particular developer of our repository)
```
            tty_prefix:
                - node
                - node_modules/webpack-dashboard/bin/webpack-dashboard.js
                - '%webpack_dashboard_args%'
                - "--"
```

The `webpack_dashboard_args` could have the `-disable` value or nothing

Would be nice to reopen this issue and implement the `-disable` flag
