### ISSUE TITLE
Passthrough commands (Nodemon)

### ISSUE THREAD

**Issue by rijkvanzanten** [FormidableLabs/webpack-dashboard#130]
I use Nodemon to automagically restart the server when the server code changes. Nodemon can be manually restarted by typing `rs` but this command isn't passed through by webpack-dashboard. Is this something that can be implemented or is there another way to achieve the same goal?
# 

My npm dev script:
`webpack-dashboard -m  -- nodemon --watch app/server --delay 2s build/server.dev.js`

I'm using the default Mac Terminal app.

webpack-dashboard `v0.1.8`
# 

Thanks in advance

**Comment by kenwheeler** [comment]
I've never actually done that before, so I'm going to look into how that works and see if I can forward it.

**Comment by jasonwilson** [comment]
Check out the examples here: https://github.com/FormidableLabs/nodejs-dashboard/issues/9

**Comment by falconxunit** [comment]
rs
