### ISSUE TITLE
All dashboard fields are empty. Windows 10

### ISSUE THREAD

**Issue by Kamilius** [FormidableLabs/webpack-dashboard#134]
Description:
When I'm trying to run dashboard for webpack-dev-server from Win10 CMD, dashboard opens but all fields are empty and not reflecting any status. App is in ReactJS, so no node index.js.

Screenshot:
![dashboard](https://cloud.githubusercontent.com/assets/3115794/19837232/009974ac-9ebe-11e6-94b6-a0f0faa64208.png)

Steps to reproduce:
Simply starting dashboard with `npm start`
1. package.json:

``` json
"scripts": {
    "start": "webpack-dashboard -- webpack-dev-server --content-base src --inline --hot --port 3000 --open",
  }
```
1. webpack.config.js

``` js
var debug = process.env.NODE_ENV !== 'production'
var Dashboard = require('webpack-dashboard')
var DashboardPlugin = require('webpack-dashboard/plugin')
var dashboard = new Dashboard()

module.exports = {
  devtool: debug ? 'eval-source-map' : null,
  plugins: debug ? [
    new DashboardPlugin(dashboard.setData()),
  ] : [],
}

```
###### More Details
- What operating system are you on?
  Windows 10
- What terminal application are you using?
  Native CMD || PowerShell || Git bash for windows, same effect everywhere
- What version of webpack-dashboard are you using?
  v0.2.0
- What is the output of running `echo $TERM`?
  `xterm` within git's bash

**Comment by kenwheeler** [comment]
If you are using the bin in package.json you dont need to `new Dashboard()` or pass setData as an argument to the plugin
