### ISSUE TITLE
Using angular-cli and angular 2 with webpack-dashboard when using: ng serve

### ISSUE THREAD

**Issue by radrad** [FormidableLabs/webpack-dashboard#137]
Can I use webpack-dashboard with Angular2 angular-cli npm package on Windows 7+.

webpack-dev-server@2.1.0-beta.9 is dependency of angular-cli - v1.0.0-beta.19-3  package.

This file: E:\a2playground\node_modules\angular-cli\tasks\serve-webpack.js
has this code:
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = Task.extend({
    run: function (commandOptions) {
        var ui = this.ui;
        var webpackCompiler;

        webpackCompiler = webpack(config);
        webpackCompiler.apply(new ProgressPlugin({
            profile: true,
            colors: true
        }));
***MY CODE***

and:
        ui.writeLine(chalk.green((_a = ["\n      **\n      NG Live Development Server is running on\n      http", "://", ":", ".\n      **\n    "], _a.raw = ["\n      **\n      NG Live Development Server is running on\n      http", "://", ":", ".\n      **\n    "], common_tags_1.oneLine(_a, commandOptions.ssl ? 's' : '', commandOptions.host, commandOptions.port))));
        var server = new WebpackDevServer(webpackCompiler, webpackDevServerConfiguration);

I tried adding this code (where I have ***MY CODE*** above): 
var DashboardPlugin = require('webpack-dashboard/plugin');
webpackCompiler.apply(new DashboardPlugin());

... But it is not reflected in cmd window. 

I also tried tried modifiying: E:\a2playground\node_modules\webpack-dev-server\lib\Server.js
by adding:
options.lazy = true; 
... But it didn't change a thing.

So can I modify npm installed package as a dependency of another one? 

Can you provide me with an example of angular-cli integration with webpack-dashboard
Thanks,
Rad

**Comment by kenwheeler** [comment]
you *should* be able to. What term are you using?

**Comment by sebbi08** [comment]
Hi i just tried it and it worked for me

i added 

`var DashboardPlugin = require('webpack-dashboard/plugin');`

and

`compiler.apply(new DashboardPlugin());`

to
...\node_modules\angular-cli\tasks\serve-webpack.js

and than changed the start script in the package.json from

`ng serve`

to

`webpack-dashboard -- ng serve`

**Comment by Nizam-Ahamed** [comment]
nefahamed@gmail.com
