### ISSUE TITLE
Scrolling in Hyper fiddly

### ISSUE THREAD

**Issue by alberto2000** [FormidableLabs/webpack-dashboard#139]
Scrolling in Hyper (hyper.is) is fiddly and not smooth at all basically useless.

====================================================================

- MacOs Sierra
- Hyper.is
- Latest webpack-dashboard
- xterm-256color

**Comment by kenwheeler** [comment]
Have you tried other blessed based apps in Hyper? Is it just webpack-dashboard thats fiddly, or is everything?

**Comment by alberto2000** [comment]
No I haven't tried other blessed based apps in Hyper yet

**Comment by rubencodes** [comment]
Wanted to share this here in case it's of any help. https://github.com/zeit/hyper/issues/1555

**Comment by alberto2000** [comment]
Not sure if this is related - I have no rendering issues, neither on Mac nor on Linux. It's just the scrolling that's choppy and practically unusable

**Comment by ryan-roemer** [comment]
I downloaded `hyper` and ran it with `webpack-dashboard@^1.0.1` and everything appears to be OK (scroling, resizing, etc.)

Can anyone encountering issues try upgrading and report back if any issues persist? If so, please open a minimal repository with install + reproduction steps so we can jump in quickly and figure things out. Thanks!

**Comment by ryan-roemer** [comment]
Closing as there are no updated reports or reproductions for us to work with. If the issue persists in `webpack-dashboard@latest`, please create a minimal repository with install + reproduction steps to properly diagnose what's going on. Thanks!
