### ISSUE TITLE
Issues with npm post scripts

### ISSUE THREAD

**Issue by t0rrro** [FormidableLabs/webpack-dashboard#14]
I can't get this project to work with npm script build setup.
I have this 
```
    "build:dev": "webpack --config config/webpack.dev.js --quiet",
    "postbuild:dev": "npm run generate_html",
```
The config creates the dashboard plugin and runs the dashboard, but the post script isn't run until the dashboard is killed

**Comment by kenwheeler** [comment]
Thats weird. This is with a project that had a 'watch' style dev server running?

**Comment by t0rrro** [comment]
Yes, but I was just running this build command. The post script chain was never run until I quit the dashboard. I like this project, but doesn't work with my setup.

**Comment by kenwheeler** [comment]
but with a regular webpack dev server it did run?

**Comment by ryan-roemer** [comment]
Don't `post<lifecycle>` commands only fire after a termination of the `<lifecycle>` command? If so, does `build:dev` keep a process open?

**Comment by t0rrro** [comment]
Yes, webpack dev server works correctly as I don't use any post commands. If I switch to a pre command for this build script it works correctly as well. It would be ideal if I could keep it as post. But this may not be possible.

**Comment by kenwheeler** [comment]
can you post a gist of your package.json?

**Comment by t0rrro** [comment]
It's the dashboard that keeps the process open. `post<lifecycle>` commands may not work with this setup.

@kenwheeler Sure, https://gist.github.com/t0rrro/26873a831552f336d1216646bcc52a6e

**Comment by kenwheeler** [comment]
You will probably want to create a separate webpack config for devserver specifically, if you are sharing it with a dev build.
