### ISSUE TITLE
HMR not working when webpack-dashboad is using 

### ISSUE THREAD

**Issue by codeVerine** [FormidableLabs/webpack-dashboard#145]
Hot module replacement is not working when webpack-dasboard used with `'webpack/hot/only-dev-server'` webpack entry. It is working fine if we use `'webpack/hot/dev-server'` entry instead of `'webpack/hot/only-dev-server'`

Webpack entry section in config:

`entry: {
    application: [
      'webpack-dev-server/client?http://localhost:3000',
      'webpack/hot/only-dev-server',
      'react-hot-loader/patch',
      path.resolve(ROOT_PATH, '../src/index'),
    ],
    vendor: ['react', 'react-dom', 'react-redux', 'react-router', 'react-router-redux', 'redux']
  },`

Server.js:

`new WebpackDevServer(webpack(config), {
  noInfo: true,
  hot: true,
  publicPath: config.output.publicPath,
  stats: {
    colors: true
  },
  historyApiFallback: true,
  contentBase: path.join(__dirname, 'build'),
}).listen(PORT, IP, function (err, result) {
  if (err) { return console.log(err); }
  console.log(`Listening at http://${IP}:${PORT}`);
});`

###### More Details

- What operating system are you on?
Kubuntu 15.04
- What terminal application are you using?
Terminator
- What version of webpack-dashboard are you using?
"webpack-dashboard": "^0.2.1"

**Comment by kenwheeler** [comment]
Do you have a repo I can try with?
