### ISSUE TITLE
Dashboard only shows log

### ISSUE THREAD

**Issue by miguelramos** [FormidableLabs/webpack-dashboard#146]
> Please provide a description of the bug / issue, and provide the details below:

Dashboard only show log screen with angular 2 and typescript configuration.

###### If the issue is visual, please provide screenshots here

![captura de ecra 2017-01-18 as 02 01 18](https://cloud.githubusercontent.com/assets/495720/22047983/3f3c31c0-dd22-11e6-8d95-c9f1c30a418d.png)

###### Steps to reproduce the problem

yarn start

###### Please provide a gist of relevant files

 
```
1. package.json (specifically the script you are using to start the dashboard)
2. webpack.config.js
3. index.js (Your express based dev server, if applicable)

====================================================================

###### More Details

- What operating system are you on? OSX El Capitan 10.11.6
- What terminal application are you using? iTerm
- What version of webpack-dashboard are you using? "webpack-dashboard": "^0.2.1"
- What is the output of running `echo $TERM`? xterm-256color

**Comment by pgib** [comment]
I had the same issue until I moved the DashboardPlugin to the end of the plugins list.

**Comment by kenwheeler** [comment]
^

**Comment by miguelramos** [comment]
That doesn't work. The same thing. Found on issues also people talking about put it on the top as first, but the funny thing is closing an issue without any reply. Thanks but no thanks.

**Comment by kenwheeler** [comment]
Actually, it looks like you are setting the port to 3001, but not also setting that port when instantiating the DashboardPlugin

**Comment by kenwheeler** [comment]
let me know if that fixes it

**Comment by scrambled2k3** [comment]
I am having the same issue, I am not using a custom port and I am instantiating it through my compiler.  This is with the latest version of webpack-dashboard (0.3.0)

```javascript
var browserSync = require('browser-sync');
var webpack = require('webpack');
var webpackDevMiddleware = require('webpack-dev-middleware');
var webpackHotMiddleware = require('webpack-hot-middleware');
var webpackConfigBuilder = require('../webpack.config');
var webpackConfig = webpackConfigBuilder('development');
var historyApiFallback = require('connect-history-api-fallback');

var Dashboard = require('webpack-dashboard');
var DashboardPlugin = require('webpack-dashboard/plugin');

var bundler = webpack(webpackConfig);

var dashboard = new Dashboard();

bundler.apply(new DashboardPlugin(dashboard.setData));

browserSync({
  server: {
    baseDir: 'src',

    middleware: [
      historyApiFallback(),

      webpackDevMiddleware(bundler, {
        quiet: true,
        publicPath: webpackConfig.output.publicPath,
        stats: { colors: true },
        noInfo: true
      }),
      webpackHotMiddleware(bundler)
    ]
  },
  files: [
    'src/*.html'
  ],
  logLevel: 'silent'
});
```

**Comment by kenwheeler** [comment]
if you remove logLevel silent does that change anything?

**Comment by kenwheeler** [comment]
or noInfo true

**Comment by xgz123** [comment]
same issue. 
~~~bash
# npm i -g webpack-dashboard

# package.json
webpack-dashboard  -- node devServer.js
~~~

**Comment by kenwheeler** [comment]
@xgz123 can you provide a little more info than that. can i see your webpack config

**Comment by xgz123** [comment]
@kenwheeler only in package.json,  my webpack config file has no code related to this . I have split my config to serveral files, so I won't paste it here.

**Comment by kenwheeler** [comment]
@xgz123 your webpack config requires adding the webpack-dashboard plugin to it. If you aren't doing that, thats why. If you are doing that, I need some details here to help you

**Comment by xgz123** [comment]
@kenwheeler thanks , I didn't add this to webpack config...

**Comment by kenwheeler** [comment]
@xgz123 np, enjoy

**Comment by scrambled2k3** [comment]
Ok, I removed both 'noInfo: true' and "logLevel: 'silent'" both individually and together.  It still didn't work.  Note, I can rollback to the previous version, 0.2.1, and this configuration works fine.

**Comment by kenwheeler** [comment]
interesting. I'll troubleshoot this, suspecting I need to detect parent process.

**Comment by kenwheeler** [comment]
@scrambled2k3 can you switch to not instantiating the dashboard from your webpack config and let me know if it works?

**Comment by miguelramos** [comment]
Problem fixed with the new version of dashboard, removed port args from package.json and order of plugins doesn't need to be first or last, only you need is to run it on dev mode or will hang the script if run on prod.

**Comment by astoltzfus** [comment]
Has anyone used webpack-dashboard with webpack-dev-server? I too only get the log when trying to configure the dashboard.

Here's a gist with the relevant script, plugin, setup, and other questions answered.
https://gist.github.com/astoltzfus/907fd16df2de9feebfe58b8da88fc12a

**Comment by abruzzihraig** [comment]
You don't need to care about the order of the plugin list. Just setting the port into both of config file and CLI parameters, then you will get all information on the Dashboard.

![image](https://cloud.githubusercontent.com/assets/3356523/23729899/9917f734-04b8-11e7-9235-9076298e71e3.png)

You can try to update configs like below:
```
const DashboardPlugin = require('webpack-dashboard/plugin');
...
plugins: [
        new DashboardPlugin({ port: 9991 }),
        new webpack.HotModuleReplacementPlugin()
    ]
````

```
"scripts": {
    "start": "webpack-dashboard -p 9991 -- webpack-dev-server --config webpack.config.js --env=dev --open --colors"
}
```

**Comment by Piliponful** [comment]
I removed the port from configuration and it worked for me.

**Comment by ghostsquad** [comment]
@abruzzihraig what background image is that?
