### ISSUE TITLE
Shortcut Log Scrolling

### ISSUE THREAD

**Issue by 3DEsprit** [FormidableLabs/webpack-dashboard#147]
First off, I absolutely love WD, and everything you guys make! Huge props!

[Feature Request]: Log Scrolling

So far I have not found anything anywhere related to scrolling through the logs, except via the mouse wheel. One thing I did like with the terminal was being able to use PgUp, PgDn to scroll through the logs, and doing this with the mouse through 500 lines is a bit much. Am I missing an existing feature? If not, how feasible is it to offer shortcut-based scrolling?

- What operating system are you on? Linux
- What terminal application are you using? VSCode/Atom's Terminal Fusion (platformio-ide-terminal)/Quake/iTerm
- What version of webpack-dashboard are you using? 0.3.0
- What is the output of running `echo $TERM`? xterm/xterm-256color/vt100

**Comment by kenwheeler** [comment]
This might help with the windows stuff too. I'll look into it. What are you thinking, down and up arrows for line, page up and down for page?

**Comment by 3DEsprit** [comment]
Sweet! 

Yeah, the usual Up/Down PgUp/PgDn schema would be dope as hell.

**Comment by 3DEsprit** [comment]
You rock @carlospaelinck ! Thanks so much for the feature update, and love that you added two different methods for each direction based on total lines scrolled.
