### ISSUE TITLE
Is there a way to configure log verbosity?

### ISSUE THREAD

**Issue by NicholasDunham** [FormidableLabs/webpack-dashboard#148]
Webpack has several ways to configure log verbosity, including `quiet`, `noInfo`, and the `stats` object. This allows the user to omit from the logs information that is, in the wise words of the webpack-dashboard README file, "mostly noise and scrolly and not super helpful."

Unfortunately, I can't seem to omit that noise from the webpack-dashboard logs window. I have Webpack set to `quiet` mode, which at least prevents it from printing the logs twice, but what I'd like is to be able to configure webpack-dashboard to print only useful logs—ideally, with the granularity of the `stats` object.

One way this would help is that the initial "Project is running at http://localhost:8080" (or whatever) message would stay on screen (barring any errors), so I could easily Cmd-click it to open it in my browser without needing to scroll.

Am I overlooking something obvious? If not, is there any chance of this capability being added? I might find time to do a pull request if someone can point me in the right direction—I haven't looked closely enough at the code yet to see what would need to be changed.

**Comment by nlutterman** [comment]
Hey, @NicholasDunham, I took a look into this in another issue that's pretty much discussing the same topic.

You can see my recommendations: [here](https://github.com/FormidableLabs/webpack-dashboard/issues/149#issuecomment-283444127).

If you make the first change that I suggested then you'll be able to use webpack's own log configuration to use as the output for the log in webpack-dashboard.
