### ISSUE TITLE
webpack-dashboard immediately quits once it loads

### ISSUE THREAD

**Issue by carlodicelico** [FormidableLabs/webpack-dashboard#15]
I'm using a pretty straightforward webpack.config.dev.js and my npm start maps to `"start": "NODE_ENV=development webpack-dev-server --config webpack.config.dev.js --colors --history-api-fallback --progress --inline --watch --hot --debug",`

When I run npm start, webpack-dashboard fires up and once the app is compiled, it immediately quits and leaves me at the normal webpack-generated output. I tried this without `--watch` and saw the same results.

**Comment by appsforartists** [comment]
It's not made as clear in the directions as it probably could be, but you need to set your server config to `quiet`.
