### ISSUE TITLE
Webpack doesn't exit

### ISSUE THREAD

**Issue by controversial** [FormidableLabs/webpack-dashboard#151]
I have `new DashboardPlugin()` at the end of my `plugins` list in my `webpack.config.js`. This works great when I'm using `webpack-dev-server`, which I use with `webpack-dashboard`. However, I keep a clone of my repo on a server as well. There, I just run `webpack` to compile static assets. The `webpack` command never exits if I have `new DashboardPlugin()` in my config file.

How should I work around this? I want to use `webpack-dashboard` in my project, but it's annoying that it prevents `webpack` from exiting.

**Comment by ralphsmith80** [comment]
Same issue here. It looks like an issue with the handler. Doing the following will cause it to exit as desired, but then the dashboard doesn't get updated.

```
new DashboardPlugin(() => {})
```

**Comment by kkerr1** [comment]
Note that in the pre-release 1.x versions this manifests in an actually error looking something like.

```
node_modules/webpack-dashboard/plugin/index.js:57
      inspectpack[action]({
                 ^

TypeError: Cannot read property 'sizes' of undefined
```

However, I think a fix is possible leveraging the `watch-run` versus the `run` interface. I am working on that.

**Comment by chollier** [comment]
did you ever figure out?

**Comment by ryan-roemer** [comment]
The error `TypeError: Cannot read property 'sizes' of undefined` has already been solved.

@chollier / anyone else -- If this still is an issue in latest `webpack-dashboard`, can you create a new repository with the minimal code + reproduction steps to show the error so we can dig in more and diagnose?

**Comment by arty-name** [comment]
I have also encountered this bug and here is the [minimal project to demonstrate it](https://github.com/arty-name/webpack-dashboard-hangs). Could you please check it out, @ryan-roemer?

**Comment by ryan-roemer** [comment]
@arty-name -- That repository fails when I run `webpack` with:

```
/Users/rye/scm/vendor/arty-name-webpack-dashboard-hangs/node_modules/webpack/bin/convert-argv.js:507
				throw new Error("'output.filename' is required, either in config file or as --output-filename");
				^

Error: 'output.filename' is required, either in config file or as --output-filename
    at processOptions (/Users/rye/scm/vendor/arty-name-webpack-dashboard-hangs/node_modules/webpack/bin/convert-argv.js:507:11)
    at processConfiguredOptions (/Users/rye/scm/vendor/arty-name-webpack-dashboard-hangs/node_modules/webpack/bin/convert-argv.js:150:4)
    at module.exports (/Users/rye/scm/vendor/arty-name-webpack-dashboard-hangs/node_modules/webpack/bin/convert-argv.js:112:10)
    at yargs.parse (/Users/rye/scm/vendor/arty-name-webpack-dashboard-hangs/node_modules/webpack/bin/webpack.js:171:41)
    at Object.Yargs.self.parse (/Users/rye/scm/vendor/arty-name-webpack-dashboard-hangs/node_modules/yargs/yargs.js:533:18)
    at Object.<anonymous> (/Users/rye/scm/vendor/arty-name-webpack-dashboard-hangs/node_modules/webpack/bin/webpack.js:152:7)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
```

That said, this issue _may_ be related to #215 -- can you try updating to just-released `^1.0.1` and if the issue persists update your minimal repository so that I can actually see the error? Thanks!

**Comment by ryan-roemer** [comment]
Actually, I fixed your repository with:

```diff
diff --git a/package.json b/package.json
index 72d6161..6c1d441 100644
--- a/package.json
+++ b/package.json
@@ -10,6 +10,6 @@
   "license": "ISC",
   "dependencies": {
     "webpack": "^3.8.1",
-    "webpack-dashboard": "^1.0.0"
+    "webpack-dashboard": "^1.0.1"
   }
 }
diff --git a/webpack.config.js b/webpack.config.js
index e2691fd..898157c 100644
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -2,4 +2,10 @@ const DashboardPlugin = require('webpack-dashboard/plugin');
 
 new DashboardPlugin();
 
-module.exports = {};
+module.exports = {
+  entry: "./index",
+  output: {
+    path: `${__dirname}/dist`,
+    filename: "build.js"
+  }
+};
diff --git a/yarn.lock b/yarn.lock
index 5d71cc7..2e3a17d 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -2557,9 +2557,9 @@ watchpack@^1.4.0:
     chokidar "^1.7.0"
     graceful-fs "^4.1.2"
 
-webpack-dashboard@^1.0.0:
-  version "1.0.0"
-  resolved "https://artifactory.setu.gkh-setu.de/api/npm/npm/webpack-dashboard/-/webpack-dashboard-1.0.0.tgz#b7a27884f21a0b6fb0107ea9a60d7fdcc52ca167"
+webpack-dashboard@^1.0.1:
+  version "1.0.1"
+  resolved "https://registry.yarnpkg.com/webpack-dashboard/-/webpack-dashboard-1.0.1.tgz#d1f329cbdab758b831cb23dc496ea72e6f9c1317"
   dependencies:
     babel-core "^6.24.0"
     babel-traverse "^6.23.1"
```

and confirmed the issue exists in `1.0.0` and is **fixed** in `1.0.1`! 🎉

**Comment by arty-name** [comment]
Sweet! Thank you for the instant fix, @ryan-roemer! 
Sorry for the sub-par minimal case, on my setup webpack wasn’t throwing errors, just giving a warning.

**Comment by ryan-roemer** [comment]
@arty-name -- Haha, no worries.

And thanks are actually in order for @tschaub who fixed this two weeks ago in https://github.com/FormidableLabs/webpack-dashboard/pull/215 (we just hadn't had a chance to publish it until today). 🎉

**Comment by haf** [comment]
This is an issue with webpack 3 and dashboard 2.0, even when using the 'apply' workaround:

Doesn't hang:

```
    plugins:
      (prod
        ? [ extractCSS, extractLESS, extractSTYL ]
        // https://github.com/FormidableLabs/webpack-dashboard/issues/125
        : [ //{ apply: function() {
            //    const dashboard = new DashboardPlugin({color: 'cyan'});
            //    dashboard.apply.apply(dashboard, arguments);
            //  }
            //}
          ]
```

hangs:

```
    plugins:
      (prod
        ? [ extractCSS, extractLESS, extractSTYL ]
        // https://github.com/FormidableLabs/webpack-dashboard/issues/125
        : [ { apply: function() {
                const dashboard = new DashboardPlugin({color: 'cyan'});
                dashboard.apply.apply(dashboard, arguments);
              }
            }
          ]
```

```

webpack-dashboard@^2.0.0:
  version "2.0.0"
  resolved "https://registry.yarnpkg.com/webpack-dashboard/-/webpack-dashboard-2.0.0.tgz#70db22e7bb5b12b4a7fde82de87ce01eed8d921c"
  dependencies:
    blessed "^0.1.81"
    commander "^2.15.1"
    cross-spawn "^6.0.5"
    filesize "^3.6.1"
    handlebars "^4.0.11"
    inspectpack "^3.0.1"
    most "^1.7.3"
    socket.io "^2.1.1"
    socket.io-client "^2.1.1"


webpack@^3.9.1:
  version "3.12.0"
  resolved "https://registry.yarnpkg.com/webpack/-/webpack-3.12.0.tgz#3f9e34360370602fcf639e97939db486f4ec0d74"
  dependencies:
    acorn "^5.0.0"
    acorn-dynamic-import "^2.0.0"
    ajv "^6.1.0"
    ajv-keywords "^3.1.0"
    async "^2.1.2"
    enhanced-resolve "^3.4.0"
    escope "^3.6.0"
    interpret "^1.0.0"
    json-loader "^0.5.4"
    json5 "^0.5.1"
    loader-runner "^2.3.0"
    loader-utils "^1.1.0"
    memory-fs "~0.4.1"
    mkdirp "~0.5.0"
    node-libs-browser "^2.0.0"
    source-map "^0.5.3"
    supports-color "^4.2.1"
    tapable "^0.2.7"
    uglifyjs-webpack-plugin "^0.4.6"
    watchpack "^1.4.0"
    webpack-sources "^1.0.1"
    yargs "^8.0.2"


```

**Comment by ryan-roemer** [comment]
@haf -- This issue refers to problems and fix to portions of webpack-dashboard that don't even exist anymore (e.g., there's no inspectpack daemon). If you want us to take a look, can you please create a new issue and link to a new minimal repository with install + error reproduction steps and we'll clone it, verify the error, and diagnose. Thanks!

**Comment by haf** [comment]
@ryan-roemer Seems like inspectpack is still required https://www.npmjs.com/package/webpack-dashboard? Are you saying that dep is gone?

**Comment by ryan-roemer** [comment]
No, I'm saying that the inspectpack Daemon that was the root of all this issue is gone. Old inspectpack used real generated files and launched a separate Daemon to parallel process stuff and min + gz

New `inspectpack@3` is a from-scratch rewrite that consumes only the stats object in-memory (available to any webpack plugin and here proxied stratight up from `webpack-dashboard`). It now is completely just JS functions that outputs our stats items without any extra moving parts like before.
