### ISSUE TITLE
Info for progress, modules, assets are not displayed

### ISSUE THREAD

**Issue by AvraamMavridis** [FormidableLabs/webpack-dashboard#153]
I am not getting info for progress, modules, assets etc
<img width="1424" alt="screen shot 2017-03-04 at 19 33 26" src="https://cloud.githubusercontent.com/assets/283690/23581309/c9e26d7c-0111-11e7-8cda-58cebcb0a393.png">

in my package.json I have 

```
    "dashboard": "webpack-dashboard -- webpack-dev-server --env=dev --progress --profile --colors --config webpack.config.js",

```

And my `webpack.config` looks like:

```
var path = require('path');
var webpack = require('webpack');
var plugins = require('./webpack.plugins');
const readFile = filePath => fs.readFileSync(path.resolve(filePath)).toString();
const fs = require('fs');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = function (options) {
  return {
    devtool: 'source-map',
    entry: [
      `./app/src/config/config.${ options.env }.js`,
      'mycs-hash',
      'scene-lib',
      'whatwg-fetch',
      'babel-polyfill',
      './app/src/index.js'
    ],
    performance: {
      hints: 'warning'
    },
    output: {
      path: path.join(__dirname, 'dist'),
      filename: 'bundle.js',
      publicPath: './'
    },
    plugins: [
      new webpack.HotModuleReplacementPlugin(),
      new ExtractTextPlugin('styles.css'),
    ].concat(plugins),
    devServer: {
      contentBase: path.join(__dirname, 'dist'),
      compress: true,
      port: 8000,
      clientLogLevel: 'info',
      historyApiFallback: true
    },
    stats: {
      // Remove built modules information.
      modules: true,
      // Remove built modules information to chunk information.
      chunkModules: true,
      colors: true
    },
    module: {
      loaders: [
        {
          test: /\.jsx?$/,
          loaders: [
            'babel-loader'
          ],
          include: path.join(__dirname, 'app')
        },
        {
          test: /\.scss$/,
          loader: 'style-loader?sourceMap!css-loader?modules&importLoaders=1&localIdentName=[name]_' +
              '_[local]___[hash:base64:5]!sass-loader'
        },
        {
          test: /\.sass$/,
          loader: ExtractTextPlugin.extract({
            fallbackLoader: 'style-loader',
            loader: 'css-loader!sass-loader',
          }),
        },
        {
          test: /\.html$/,
          use: {
            loader: 'html-loader',
            options: {
              minimize: false
            }
          }
        },
        {
          test: /\.(gif|png|jpe?g|svg)$/i,
          loaders: [
            'file-loader',
            {
              loader: 'image-webpack-loader',
              query: {
                progressive: true,
                optimizationLevel: 7,
                interlaced: false,
                pngquant: {
                  quality: '65-90',
                  speed: 4
                }
              }
            },
          ]
        }
      ]
    }
  };
};
```

Removing the `new webpack.HotModuleReplacementPlugin(),` enables the progress, but still not modules/assets info

**Comment by adack123** [comment]
Hey, @AvraamMavridis 

Have you tried...

```javascript
var DashboardPlugin = require('webpack-dashboard/plugin');
```

Usage...

```javascript
  plugins: [
      new webpack.HotModuleReplacementPlugin(),
      new ExtractTextPlugin('styles.css'),
      new DashboardPlugin()
 ]
```

Let me know how it goes!

**Comment by AvraamMavridis** [comment]
yep, all good. Thx!

**Comment by mbruggenwirth** [comment]
Got the same problem as above.
I don't use HotModuleReplacementPlugin but still no progress.

![schermafbeelding 2017-09-25 om 12 36 50](https://user-images.githubusercontent.com/6103920/30804608-5a3a340e-a1ee-11e7-8582-b2d8a59e5f22.png)

My package.json:
 "dev": "webpack-dashboard -- webpack-dev-server --env.development",

Here my Webpack config.

`const path = require('path');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const autoprefixer = require('autoprefixer');
const UglifyJSPlugin = require('uglifyjs-webpack-plugin');
const OptimizeCssAssetsPlugin = require('optimize-css-assets-webpack-plugin');
const DashboardPlugin = require('webpack-dashboard/plugin');

module.exports = environment => {
    const env = environment === undefined ? {development : true} : environment;

    const javascript = {
        test: /\.(js)$/,
        exclude: /(node_modules|bower_components)/,
        use: [{
            loader: "babel-loader",
            options: { presets : ['env'] }
        }]
    };

    const postcss = {
        loader: 'postcss-loader',
        options: {
            plugins() { return [
                autoprefixer({ browsers: 'last 3 versions' })
            ]; }
        }
    };

    const styles = {
        test: /\.(scss)$/,
        exclude: [
            path.resolve(__dirname, "assets")
        ],
        loader: ExtractTextPlugin.extract({
            fallback: "style-loader",
            use: ["css-loader", postcss, "sass-loader"]
        })
    };

    const globbing = {
        test: /\.(scss)$/,
        enforce: "pre",
        use: "import-glob-loader"
    };

    const assets = {
        test: /\.(png|jpg|gif|svg)$/,
        exclude: /node_modules/,
        loader: "url-loader",
    };

    const svg = {
        test: /\.svg$/,
        loader: "file-loader?name=../[path][name].[ext]"
    };

    const fonts = {
        test: /\.(eot|svg|ttf|woff|woff2)$/,
        loader: "file-loader?name=../[path][name].[ext]"
    };

    function getPlugins() {
        let plugins = [
            new ExtractTextPlugin('main.css'),
        ];

        if(env && env.production) {
            plugins = [...plugins, new OptimizeCssAssetsPlugin(), new UglifyJSPlugin()];
        }

        plugins = [...plugins, new DashboardPlugin({ port: 9000 })];

        return plugins;
    }

    function getRules(){
        return [javascript, globbing, styles, assets, svg, fonts];
    }

    return {
        entry: {
            app: "./src/js/app.js",
        },
        devtool: "source-map",
        devServer: {
            contentBase: path.join(__dirname, 'dist'),
            compress: true,
            port: 9000,
            clientLogLevel: 'info',
            historyApiFallback: true
        },
        output: {
            path: path.resolve(__dirname, "dist"),
            filename: '[name].js'
        },
        module: {
            rules: getRules()
        },
        plugins: getPlugins()
    };
};
`
