### ISSUE TITLE
Only showing .js bundle in assets tab

### ISSUE THREAD

**Issue by mjanssen** [FormidableLabs/webpack-dashboard#159]
> Please provide a description of the bug / issue, and provide the details below:

Hey there :). I'm using the webpack dashboard for a basic setup. I'm using the webpackhtmlplugin to dynamically add my JavaScript to my index.html. Webpack dashboard only shows me `main.bundle.js` in the assets tab.

###### Screenshot

<img width="1071" alt="screen shot 2017-03-30 at 17 18 18" src="https://cloud.githubusercontent.com/assets/1145427/24511765/eeafeb2e-156c-11e7-869a-fb43ae94eef7.png">

###### Relevant files

Git page containing all files: https://github.com/mjanssen/webpack-vue-hot-module-reloading

Webpack config is stored within the `./webpack` directory. `package.json` runs webpack dashboard using the follow command:

`webpack-dashboard -p 9991 -c cyan -- webpack-dev-server --config ./webpack/webpack.config.js --client-log-level warning`

**Comment by kenwheeler** [comment]
What are you expecting to see there?

**Comment by mjanssen** [comment]
Hey Ken, I expect to see the modules that are compiled (App.js), rather than the complete bundle.

**Comment by kenwheeler** [comment]
I'm not sure what you mean. The assets tab is the output of webpack. So that main bundle is what webpack outputs.

**Comment by mjanssen** [comment]
I'm sure I have seen some setups outputting the components separately, instead of a complete bundle. But if this is based on the webpack output, my guess is my webpack configuration should be edited.

**Comment by kenwheeler** [comment]
Are you trying to do code splitting? Or do you actually want each component output as a bundled distribution version?

**Comment by mjanssen** [comment]
I will try to figure out how I can implement code splitting. This will (if I'm correct) show separate files, rather than a complete bundle. I will close this issue, since it's not a dashboard related issue...

Thanks for checking though :)
