### ISSUE TITLE
Modules, Assets, Status, Operation and Progress do not show anything

### ISSUE THREAD

**Issue by XidongHuang** [FormidableLabs/webpack-dashboard#161]
> Please provide a description of the bug / issue, and provide the details below:

Only `'log'` displays information.

###### Screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/13139446/24763456/741334a4-1abf-11e7-9e76-430df4790120.png)

====================================================================

###### Steps to reproduce the problem
npm run dev
====================================================================

###### Please provide a gist of relevant files

1. package.json (specifically the script you are using to start the dashboard):
```
{
  ...
  "scripts": {
    "build": "rimraf ./dist && NODE_ENV=production webpack",
    "dev": "NODE_ENV=development webpack-dashboard -- node dev-server.js",
    "dev-hot": "NODE_ENV=development webpack-dev-server --hot"
  },
...
  "devDependencies": {
   ...
    "webpack": "^2.3.3",
    "webpack-dashboard": "^0.3.0",
    "webpack-dev-server": "^2.4.2"
  }
}
```
2. webpack.config.js:
```
var path = require('path');
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var HTMLWebpackPlugin = require('html-webpack-plugin');
let DashboardPlugin = require('webpack-dashboard/plugin');

let DEVELOPMENT = process.env.NODE_ENV === 'development';
let PRODUCTION = process.env.NODE_ENV === 'production';

var entry = PRODUCTION
            ? {

                hello: './src/jsx/hello.js'
                }
            : [
                './src/jsx/hello.js',
                'webpack/hot/dev-server',
                'webpack-dev-server/client?http://localhost:9090/'
              ]

var plugins = PRODUCTION 
              ? [
                  new webpack.optimize.UglifyJsPlugin(),
                  new ExtractTextPlugin('style.[contenthash:10].css'),
                  new HTMLWebpackPlugin({
                      template: 'hello-template.html'
                  })
                
                ]
              : [
                    
                    new webpack.HotModuleReplacementPlugin(),
                    new webpack.NoEmitOnErrorsPlugin(),    
                    new DashboardPlugin({port: 9090}),
                   
                    
                ];

let cssIdentifier = PRODUCTION ? '[hash:base64:10]' : 'styles.css';

let cssLoader = PRODUCTION   
                  ? ExtractTextPlugin.extract({
                      fallbackLoader: "style-loader",
                      loader: 'css-loader?localIdentName=' + cssIdentifier
                  })
                  : ['style-loader', 'css-loader?localIdentName=' + cssIdentifier];

module.exports = {
    entry: entry,
    output: { 
        path: path.join(__dirname, './dist'),
        publicPath: PRODUCTION ? './': '',
        filename: PRODUCTION ? 'bundle.[hash:12].min.js': 'bundle.js'
    },
    module: {
        rules: [
            {
                test:/\.jsx?$/,
                exclude: /node_modules/,
                loaders: ['react-hot-loader']
            },
            {
                test: /\.jsx?$/,
                loader: 'babel-loader',
                // include: path.join(__dirname, 'src'),
                exclude: /node_modules/
                ,
                options: {
                    presets: ['react','es2015','stage-0' ]
                }
            },
            {
                test: /\.css$/,
                loaders: cssLoader
            }
            ,
           { test: /\.(png|woff|woff2|eot|ttf|svg)$/, loader: 'url-loader?limit=100000' },
        ]       
    },
        resolve: {
            extensions: [ '.js', '.jsx', '.css'],
            modules: [
            'node_modules'
        ] 
    },
    plugins: plugins
}
```
3. index.js (Your express based dev server, if applicable)

====================================================================

###### More Details

- What operating system are you on?
`Ubuntu 14.04`
- What version of webpack-dashboard are you using?
`0.3.0`
- What is the output of running `echo $TERM`?
`xterm`

**Comment by kenwheeler** [comment]
You are emitting on port 9090 via your webpack config, but not configuring that in your npm scripts with the --port option

**Comment by XidongHuang** [comment]
@kenwheeler Thanks for the quick reply.
So I tried to set 
```"dev": "NODE_ENV=development webpack-dashboard -p 9090 -- node dev-server.js"```
However, it throws an `Error: listen EADDRINUSE 127.0.0.1:9090`.
And the `:9090` port is only used when I `npm run dev`, so are there any hits for that?

The configurations about ports:
```
//webpack.config.js
...
'webpack-dev-server/client?http://localhost:9090/'
...

...
new DashboardPlugin({port:9090})
...
```
and the `dev-server.js`:
```
...
server.listen(9090, 'localhost', function(){});
```

**Comment by kenwheeler** [comment]
You probably want to change your port to something other than what dev server is using. Try 1337 or something.

**Comment by kenwheeler** [comment]
Also, you could just remove all port info from the dashboard plugin function call

**Comment by XidongHuang** [comment]
@kenwheeler Thank you sir. 
As you mentioned, I removed the argument in `new DashboardPlugin()`, 
and the `--port` in `package.json` . So the script like: `NODE_ENV=development webpack-dashboard -- node dev-server.js`. So it works well.
And I can pretend I'm an astronaut now.

**Comment by batjko** [comment]
I am getting this error as well, but I can't just remove the custom port because I run the webpack-dev-server inside a docker container... I need to expose the port from  docker so I need to know which port it is, so I set a custom port:

webpack config:
```js
entry: [
  [...],
  webpack-dev-server/client?http://localhost:8090
]
// [...]
new DashboardPlugin({ port: 7777 })
```

Running with globally installed webpack-dashboard:
```bash
$ webpack-dashboard -p 7777
```

docker-compose config:
```yml
web:
    # [...]
    command: "yarn webpack-dev-server"
    ports:
      - "8090:8090"
      - "7777:7777"
```

But no matter what custom port I use, I always get the EADDRINUSE error.
Any ideas?

**Comment by ryan-roemer** [comment]
@batjko -- If you can create a minimal repository (Dockerfile, etc. included) + install and reproduction steps, we may be able to jump in and get a better sense of what's going wrong. Thanks!

**Comment by td234** [comment]
@batjko Did you ever solve this? I am having same problem. Also running in a docker container to cannot just change the port.

Thanks

T

**Comment by batjko** [comment]
@td234 @ryan-roemer I'm afraid I had to abandon the attempt, as I just didn't have the time to rewrite a mini-version of our app (it's quite large and complex).

Perhaps someone else can give that a go? *nudge, nudge*

**Comment by zlatinivanov-je** [comment]
I ended up here looking for a solution to an error related to `EADDRINUSE`, but discovered that a service was running on the background on the same port. Once that was stopped, it all worked as expected.
