### ISSUE TITLE
Tag new version

### ISSUE THREAD

**Issue by th3fallen** [FormidableLabs/webpack-dashboard#163]
Tag new version to allow consumption of https://github.com/FormidableLabs/webpack-dashboard/pull/155 please

**Comment by IceMimosa** [comment]
+1

**Comment by th3fallen** [comment]
@exogen not sure who to ping on this but can we get some movement here?

**Comment by exogen** [comment]
On it!

**Comment by th3fallen** [comment]
![youdaman](https://i.imgflip.com/1adz9x.jpg)

**Comment by exogen** [comment]
OK, `latest` is now `0.4.0`! 🎉 

We also have `1.0.0` in the works if you'd like to experiment: `webpack-dashboard@next`!

**Comment by th3fallen** [comment]
@exogen late but are there docs for what i need to alter to play with the new version?
