### ISSUE TITLE
Attempts to compile twice

### ISSUE THREAD

**Issue by gnohj** [FormidableLabs/webpack-dashboard#170]
I tried using the latest version and I get two compiliations... on the second it hangs.

I rolled back to 0.2.1 and it seems to be working fine.

**Comment by kkerr1** [comment]
@gnohj thanks for your report. When you say latest can you confirm that you mean `1.0.0-2?` Is there any error message / stack trace for the hang?

**Comment by binarykitchen** [comment]
yeah, i have that problem too. the compilation output is printed twice. does not happen when i call webpack-dev-server directly without the dashboard.

**Comment by ryan-roemer** [comment]
Can folks update to newly released `^1.0.0` and check if this is still an issue?

If so, can someone open a minimal repository with the error and install + reproduction steps so we have something to dig in and analyze? Thanks!

**Comment by ryan-roemer** [comment]
Closing as there are no updated reports or reproductions for us to work with. If the issue persists in `webpack-dashboard@latest`, please create a minimal repository with install + reproduction steps to properly diagnose what's going on. Thanks!
