### ISSUE TITLE
Webpack 1.0.0-2 crashes on bundles with devtool: 'eval'

### ISSUE THREAD

**Issue by kkerr1** [FormidableLabs/webpack-dashboard#171]
Webpack 1.0.0-2 fails on webpack bundles generated with `devtool: 'eval'`. The error comes from inspectback. See bug https://github.com/FormidableLabs/inspectpack/issues/34

**Comment by ryan-roemer** [comment]
Fixed in https://github.com/FormidableLabs/inspectpack/pull/35
