### ISSUE TITLE
Log output huge with webpack 3

### ISSUE THREAD

**Issue by th3fallen** [FormidableLabs/webpack-dashboard#176]
> Please provide a description of the bug / issue, and provide the details below:
When building the output of the log area is the full output from webpack not the pretty verison you depict in your readme
====================================================================

###### If the issue is visual, please provide screenshots here
![](http://th3fallen.d.pr/6dwc7y.jpg)
====================================================================

###### Steps to reproduce the problem

====================================================================

###### Please provide a gist of relevant files

1. package.json (specifically the script you are using to start the dashboard)
2. webpack.config.js
3. index.js (Your express based dev server, if applicable)
https://gist.github.com/th3fallen/600c39174e51b92efe7c0d37f84e3930

====================================================================

###### More Details

- What operating system are you on? `OSX`
- What terminal application are you using? `iTerm`
- What version of webpack-dashboard are you using? `0.4.0`
- What is the output of running `echo $TERM`? `xterm-256color`

**Comment by th3fallen** [comment]
I had a previous issue about this https://github.com/FormidableLabs/webpack-dashboard/issues/149 but it was closed prematurely as it didnt actually fix the issue.

I hope im just overlooking something

**Comment by mikos** [comment]
I think this is a similar situation to the one you referenced in #149. I noticed that the `quiet` option fed to WebpackDevServer doesn't appear to do much. However setting `stats` to "minimal" or "errors-only" appears to clean up the output a lot.

**Comment by kenwheeler** [comment]
Can you try on the alpha branch?

**Comment by th3fallen** [comment]
@kenwheeler alpha being 1.0.0-3?

**Comment by kenwheeler** [comment]
Yeah

**Comment by kenwheeler** [comment]
Is this webpack 3 specific?

**Comment by th3fallen** [comment]
No i've had this issue since webpack2 and updating to 0.4.0

**Comment by th3fallen** [comment]
![](http://th3fallen.d.pr/nsijmW.jpg) is the result on the alpha branch, log is still bloated however.

**Comment by ryan-roemer** [comment]
@th3fallen -- Can you upgrade to `^1.0.0` and try again?

If the issue persists, can you create a minimal repository with install + reproduction steps so that we can jump in and more quickly figure out what's going on?

**Comment by ryan-roemer** [comment]
Closing as there are no updated reports or reproductions for us to work with. If the issue persists in `webpack-dashboard@latest`, please create a minimal repository with install + reproduction steps to properly diagnose what's going on. Thanks!
