### ISSUE TITLE
Slow startup time

### ISSUE THREAD

**Issue by appsforartists** [FormidableLabs/webpack-dashboard#18]
I'm using WebpackDevServer.  Adding WebpackDashboard makes my startup time jump from 8s to 24x (a 3x increase).

**Comment by kenwheeler** [comment]
Are you seeing slowness increasing elsewhere? I wonder if thats blessed initializing or callbacks blocking.

**Comment by appsforartists** [comment]
Haven't measured.  Will probably try it for a couple days and kill it if the rest feels slow.

At first blush (adding newlines to a file and seeing it recompile), doesn't seem unusably slow after it's up.  The increase in start time is very noticeable though.

**Comment by avanderhoorn** [comment]
I can confirm that it seems to increase timing considerably. I've tested about 4 or 5 times now and without dashboard it takes about 15s and with takes 30s. Most of the extra time is going into building the modules.

**Comment by lakshyaranganath** [comment]
Facing the same issue here.

**Comment by kenwheeler** [comment]
This might be fixed by the approach detailed in #30

**Comment by kenwheeler** [comment]
This should fix it https://github.com/FormidableLabs/webpack-dashboard/pull/50 , let me know

**Comment by kenwheeler** [comment]
This should be fixed in the latest release

**Comment by avanderhoorn** [comment]
Fixed my issues.

**Comment by Nizam-Ahamed** [comment]
nefahamed@gmail.com

**Comment by lakshyaranganath** [comment]
Fixed it. :) thanks 🎉
