### ISSUE TITLE
can not analyze bundle problems

### ISSUE THREAD

**Issue by MrZhang123** [FormidableLabs/webpack-dashboard#186]
## Problem description
when i open the webpack-dashbord and packaging , sometime the console this log
```sh
can not analyze bundle problems.
undefined
```
## Environment
MacOS 10.12.6
Webpack 3.5.5
webpack-dev-server 2.7.1

## config
//webpack config
```js
var Dashboard = require('webpack-dashboard');
var DashboardPlugin = require('webpack-dashboard/plugin');

plugins: [
    new DashboardPlugin(dashboard.setData),
  ]

//dev-server
const server = new webpackDevServer(compiler, {
    quiet: true,
})
```
What is the cause of the problem and how to solve it ?

**Comment by shangfeiSF** [comment]
me to

**Comment by ryan-roemer** [comment]
If you can provide a sample project repository with steps to reproduce the problem, we can perhaps help you more.

See this great example (https://github.com/FormidableLabs/webpack-dashboard/issues/189#issue-254846767) for how to create a reproduction for us over in diagnosis-land.

Thanks!

**Comment by ryan-roemer** [comment]
Closing as we need a full reproduction / more information to go forward.

If you're still encountering this issue, please try upgrading `webpack-dashboard`. If that doesn't solve the problem, then please create a sample repository with reproduction steps to enable us to see the issue.

See this great example (https://github.com/FormidableLabs/webpack-dashboard/issues/189#issue-254846767) for how to create a reproduction for us over in diagnosis-land.
