### ISSUE TITLE
"npm  start"  && "npm run build" are not working 

### ISSUE THREAD

**Issue by bvscsai** [FormidableLabs/webpack-dashboard#187]
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! app@0.0.0 build: `rimraf dist && webpack --progress --profile --bail`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the app@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-09-05T09_02_05_917Z-debug.log

**Comment by ryan-roemer** [comment]
Hi @bvscsai -- The exit code unfortunately doesn't tell us actionable information. If you can provide a sample project repository with steps to reproduce the problem, we can perhaps help you more.

See this great example (https://github.com/FormidableLabs/webpack-dashboard/issues/189#issue-254846767) for how to create a reproduction for us over in diagnosis-land.

Thanks!

**Comment by ryan-roemer** [comment]
Closing as we need a full reproduction / more information to go forward.

If you're still encountering this issue, please try upgrading `webpack-dashboard`. If that doesn't solve the problem, then please create a sample repository with reproduction steps to enable us to see the issue.

See this great example (https://github.com/FormidableLabs/webpack-dashboard/issues/189#issue-254846767) for how to create a reproduction for us over in diagnosis-land.
