### ISSUE TITLE
Missing info about Progress, Status, Operation, Problems etc

### ISSUE THREAD

**Issue by mbruggenwirth** [FormidableLabs/webpack-dashboard#196]
Hi, Got the same problem as #153 
I don't use HotModuleReplacementPlugin but still no information.

![schermafbeelding 2017-09-25 om 12 36 50](https://user-images.githubusercontent.com/6103920/30804608-5a3a340e-a1ee-11e7-8582-b2d8a59e5f22.png)

My package.json:
 "dev": "webpack-dashboard -- webpack-dev-server --env.development",

Here my Webpack config.
`const path = require('path');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const autoprefixer = require('autoprefixer');
const UglifyJSPlugin = require('uglifyjs-webpack-plugin');
const OptimizeCssAssetsPlugin = require('optimize-css-assets-webpack-plugin');
const DashboardPlugin = require('webpack-dashboard/plugin');

module.exports = environment => {
    const env = environment === undefined ? {development : true} : environment;

    const javascript = {
        test: /\.(js)$/,
        exclude: /(node_modules|bower_components)/,
        use: [{
            loader: "babel-loader",
            options: { presets : ['env'] }
        }]
    };

    const postcss = {
        loader: 'postcss-loader',
        options: {
            plugins() { return [
                autoprefixer({ browsers: 'last 3 versions' })
            ]; }
        }
    };

    const styles = {
        test: /\.(scss)$/,
        exclude: [
            path.resolve(__dirname, "assets")
        ],
        loader: ExtractTextPlugin.extract({
            fallback: "style-loader",
            use: ["css-loader", postcss, "sass-loader"]
        })
    };

    const globbing = {
        test: /\.(scss)$/,
        enforce: "pre",
        use: "import-glob-loader"
    };

    const assets = {
        test: /\.(png|jpg|gif|svg)$/,
        exclude: /node_modules/,
        loader: "url-loader",
    };

    const svg = {
        test: /\.svg$/,
        loader: "file-loader?name=../[path][name].[ext]"
    };

    const fonts = {
        test: /\.(eot|svg|ttf|woff|woff2)$/,
        loader: "file-loader?name=../[path][name].[ext]"
    };

    function getPlugins() {
        let plugins = [
            new ExtractTextPlugin('main.css'),
        ];

        if(env && env.production) {
            plugins = [...plugins, new OptimizeCssAssetsPlugin(), new UglifyJSPlugin()];
        }

        plugins = [...plugins, new DashboardPlugin({ port: 9000 })];

        return plugins;
    }

    function getRules(){
        return [javascript, globbing, styles, assets, svg, fonts];
    }

    return {
        entry: {
            app: "./src/js/app.js",
        },
        devtool: "source-map",
        devServer: {
            contentBase: path.join(__dirname, 'dist'),
            compress: true,
            port: 9000,
            clientLogLevel: 'info',
            historyApiFallback: true
        },
        output: {
            path: path.resolve(__dirname, "dist"),
            filename: '[name].js'
        },
        module: {
            rules: getRules()
        },
        plugins: getPlugins()
    };
};
`

**Comment by ryan-roemer** [comment]
@mbruggenwirth -- Does https://github.com/FormidableLabs/webpack-dashboard/issues/153 solve the issue for you?

If not, can you create a small repository with the minimum amount of code to reproduce your error + install / build steps so that we can see what you see and help diagnose? Thanks!

**Comment by ryan-roemer** [comment]
Closing as we need a full reproduction / more information to go forward.

If you're still encountering this issue, please try upgrading `webpack-dashboard`. If that doesn't solve the problem, then please create a sample repository with reproduction steps to enable us to see the issue.

See this great example (https://github.com/FormidableLabs/webpack-dashboard/issues/189#issue-254846767) for how to create a reproduction for us over in diagnosis-land.
