### ISSUE TITLE
Feature: Detect/switch into "prod" mode if not "dev" friendly bundle.

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/webpack-dashboard#198]
Actually detect if inspectpack can do anything with a bundle, else go into a fallback mode with say "old" wp-db stuff (full bundle size + min or whatnot).

**Comment by carlospaelinck** [comment]
I found a defect I have fixed in the branch for this while working on this story around correctly showing individual modules for Webpack 3.
