### ISSUE TITLE
[Research] Add deduplication information.

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/webpack-dashboard#2]
AFAICT the webpack compiler doesn't have access to deduplication info (when a code snippet is changed to an index reference or array of integer ref's). If this is _not_ the case, would be nice to _also_ have this information become part of the dashboard for the reason that otherwise we may be double / n+ counting code snippets that are really collapsed.

**Comment by kenwheeler** [comment]
You mean listing missed duplicates? Or something else?

**Comment by ryan-roemer** [comment]
I haven't dug that far in to how the dashboard operates, but if you're using information from just the compiler if I remember correctly it does not contain information about the duplicated code truck to how the dashboard operates, but if you're using information from just the compiler if I remember correctly it does not contain information about the deduplicated code chunks. So I guess that's another way of saying, just make sure that the math adds up for the individual code chunk sizes equaling the full production bundle size.
