### ISSUE TITLE
Passthrough Control-C

### ISSUE THREAD

**Issue by appsforartists** [FormidableLabs/webpack-dashboard#20]
Dashboard [traps Control-C and manually calls `process.exit()`](https://github.com/FormidableLabs/webpack-dashboard/blob/master/dashboard/index.js#L26-L28).  If you comment that out, it will still eat Control-C.

I have a webserver and a WebpackDevServer instance that I start up with `npm start`:

```json
    "start": "trap 'kill %1' SIGINT; dev_appserver.py ./site/ & node --stack-trace-limit=1000 ./examples/devServer.js",
```

Before Dashboard, this would start both simultaneously and kill both with Control-C.  With Dashboard, it kills `node` but leaves `python` running.  Admittedly, shell scripting is not my forté; haven't figured out how to massage it to do the right thing with Dashboard.

Advice?  Is there a way to prevent `blessed` from eating `control-c`?

**Comment by kenwheeler** [comment]
Hmmm, the blessed `ignoreLocked` option might work

**Comment by appsforartists** [comment]
Nope.  With the following code, `esc` and `q` quit webpack (but not python), and `C-c` does nothing:

```javascript
this.screen = blessed.screen({
  smartCSR: true,
  title: 'reactotron',
  dockBorders: false,
  fullUnicode: true,
  autoPadding: true,
  ignoreLocked: ['C-c']
});

this.layoutLog.call(this);
this.layoutStatus.call(this);
this.layoutModules.call(this);
this.layoutAssets.call(this);

this.screen.key(['escape', 'q'], function() {
  process.exit(0);
});
```

**Comment by kenwheeler** [comment]
Have you tried clicking the title bar of the terminal and then ctrl c'ing?

**Comment by appsforartists** [comment]
Just confirmed that doesn't change the behavior.

**Comment by kenwheeler** [comment]
This might have something to do with mouse focus trapping.

**Comment by eddiewang** [comment]
ctrl-c freezes the app and doesn't give me access to the command line. using react-boilerplate.

**Comment by kenwheeler** [comment]
@eddiewang got a branch I can check out to test?

**Comment by eddiewang** [comment]
here's the debug branch i setup: https://github.com/litdevelopers/tinder/tree/debut/wpdash

**Comment by eddiewang** [comment]
also - it doesn't seem to apply the optimizations that webpack dll setup in the same project optimizes for. usually webpack rebuilds take <350ms.

**Comment by nakul12345** [comment]
testing testing testing testing

**Comment by kenwheeler** [comment]
This should fix it https://github.com/FormidableLabs/webpack-dashboard/pull/50

**Comment by kenwheeler** [comment]
This should be fixed in the latest release
