### ISSUE TITLE
Connect / disconnect to running dev server?

### ISSUE THREAD

**Issue by avindra** [FormidableLabs/webpack-dashboard#21]
Currently, we run our `webpack-dev-server` headlessly and it restarts on its own at 3am every morning.

Is there a way that we can hook into an already running dev server, so that we can open / close the dashboard at will by connecting / disconnecting from the session?

**Comment by kenwheeler** [comment]
Here is what I would do. I'd create a class that had a handler method on it, and pass that on the initial config. Then have that class be able to add and remove a target for its handler, and when you want to connect, just create a new instance of the dashboard and register it with your class.
