### ISSUE TITLE
Running Dashboard with Multi-Script Process?

### ISSUE THREAD

**Issue by 3DEsprit** [FormidableLabs/webpack-dashboard#222]
**Issue**:

I couldn't find this in any of the issues, but it seems that WD does not like to be called within nested npm scripts, and only showing the dashboard when called in the initiating script. 

Let me give a quick example of a script layout:

**package.json**
```
"scripts": {
  "start-main": "cross-env HOT=1 electron -r babel-register ./Electron/main",
  "start-render": "webpack-dashboard -- cross-env NODE_ENV=development node --trace-warnings --max_old_space_size=2096 -r babel-register ./node_modules/webpack-dev-server/bin/webpack-dev-server --config webpack.config.development.js --progress --color --watch",
  "dev": "concurrently --kill-others \"npm run start-render\" \"npm run start-main\"",
}
```

* When using the above, and calling _dev_ the webpack-dashboard is called within the nested script _start-render_, but the dashboard is not shown, and any interaction shows garbage:

<img width="543" alt="screen shot 2017-11-12 at 15 09 18" src="https://user-images.githubusercontent.com/3156278/32703424-839dc278-c7bb-11e7-9eda-1719212d3135.png">

* If _start-render_ is run by itself, everything works as intended

* If the command is added to the initiating script the dashboard shows, but picks up all of the output from the previous scripts. 

Is there a workaround for this issue? I know I could run the webpack process by itself, but it would be great to start everything at once, especially since the example given is actually a trimmed down version of the chain I use for the app this issue stemmed from. 

**Versions**:

Webpack: 3.8.1
Webpack-Dashboard: 1.0.2
NPM: 5.5.1 
Node:  8.9.1

**Comment by ryan-roemer** [comment]
Can you open up a minimal repository with install + reproduction steps to see what you're seeing?

For reference, this issue looks likely to be related to https://github.com/FormidableLabs/webpack-dashboard/issues/214  and https://github.com/FormidableLabs/webpack-dashboard/issues/217 . Basically, if you install `blessed` and run `node node_modules/blessed/example/simple-form.js` in place of webpack-dashboard, then you have a blessed problem, not a webpack-dashboard problem.

Good luck and thanks!

**Comment by ryan-roemer** [comment]
Just saw https://github.com/FormidableLabs/webpack-dashboard/issues/218 which is potentially related. If the issue really is with `concurrently`, I may have an alternate solution that works analogously. (Something that may preserve terminal I/O better).

**Comment by 3DEsprit** [comment]
Ah, sure enough, it is in fact an issue with _concurrently_. I went ahead and re-wrote the script without concurrently to test, and WD showed up like before. It also turns out that setting the **--raw** flag for _concurrently_ will also fix this issue. 

Cheers!
