### ISSUE TITLE
Unable to install with yarn

### ISSUE THREAD

**Issue by philippkuehn** [FormidableLabs/webpack-dashboard#225]
I'm not able to install the newest version of webpack-dashboard with yarn. Installing v0.4.0 is fine.
If i run `yarn add webpack-dashboard --dev` in a fresh project folder I will get an endless loading screen:
![drfkfoniwx](https://user-images.githubusercontent.com/2500670/32774656-5091944a-c92d-11e7-94f0-d6c43de67581.png)

I'm using yarn 1.3.2 and node 8.9.1. For `npm install webpack-dashboard` everything is fine so I don't know if it's a problem of yarn or webpack-dashboard.

**Comment by ryan-roemer** [comment]
Hmmmm... I created a duplicate setup on my Macbook with yarn 1.3.2 and node 8.9.1 and then did:

```sh 
(nvm v8.9.1) rye@small ~/Desktop/TEMP_WD_YARN_224 $ yarn add webpack-dashboard --dev
yarn add v1.3.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > webpack-dashboard@1.0.2" has unmet peer dependency "webpack@*".
[4/4] 📃  Building fresh packages...
success Saved lockfile.
success Saved 175 new dependencies.
< ... SNIPPED ... >
✨  Done in 50.25s.
```

and it all worked out just fine. How long did you let the `yarn add webpack-dashboard --dev` command run before killing it? Can you try again and wait maybe 15 minutes or so and report back?

**Comment by philippkuehn** [comment]
Jep, I've waited a loooong time :) But still no luck. And I got some more warnings than you. But I have no idea, what this means :(

```
Philipps-MacBook-Pro:test philippkuehn$ yarn add webpack-dashboard --dev
yarn add v1.3.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > webpack-dashboard@1.0.2" has unmet peer dependency "webpack@*".
[4/4] 📃  Building fresh packages...
⠁
⠁
[1/3] ⠂ integer
[2/3] ⠂ farmhash
[-/3] ⠂ waiting...
[-/3] ⠂ waiting...
warning Error running install script for optional dependency: "/Users/philippkuehn/Desktop/test/node_modules/integer[3/3] ⢀ better-sqlite3: ==> /Users/philippkuehn/Desktop/test/node_modules/lzz-gyp/lzz-compiled/osx -hx hpp
[2/3] ⢀ farmhash
[-/3] ⢀ waiting...
[-/3] ⢀ waiting...
warning Error running install script for optional dependency: "/Users/philippkuehn/Desktop/test/node_modules/better-sqlite3: Command failed.\nExit code: 1\nCommand: node deps/install\nArguments: \nDirectory: /Users/philippkuehn/Desktop/test/node_modules/better-sqlite3\nOutput:\n==> cwd: /Users/philippkuehn/Desktop/test/node_modules/better-sqlite3\n==> /Users/philippkuehn/Desktop/test/node_modules/lzz-gyp/lzz-compiled/osx -hx hpp -sx cpp -k BETTER_SQLITE3 -d -hl -sl -e ./src/better_sqlite3.lzz\n==> cwd: /Users/philippkuehn/Desktop/test/node_modules/better-sqlite3\n==> node-g[-/3] ⠂ waiting...
[-/3] ⠐ waiting...
[2/3] ⠐ farmhash
[-/3] ⠄ waiting...
[-/3] ⡀ waiting...
[2/3] ⡀ farmhash
[-/3] ⡀ waiting...
[-/3] ⡀ waiting...
[1/2] ⠠ farmhash
[-/2] ⠠ waiting...
[-/2] ⠠ waiting...
[-/2] ⠠ waiting...
[-/2] ⠠ waiting...
```

**Comment by ryan-roemer** [comment]
Hmmm.... on a hunch can you separately try all of these commands in a clean directory (each one gets its own clean directory):


```
$ yarn add --dev farmhash
```

```
$ yarn add --dev integer
```

```
$ yarn add --dev better-sqlite3
```

I'm looking to see if any **hang** your terminal similarly (particularly `farmhash`). I'm not concerned about if they fail -- many/most of the commands will fail I'm guessing.

**Comment by philippkuehn** [comment]
Hey, `farmhash` is working fine. But with `integer` there is a problem.

```
Philipps-MacBook-Pro:Neuer Ordner 2 philippkuehn$ yarn add --dev integer
yarn add v1.3.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/1] ⠂ integer
error /Users/philippkuehn/Desktop/Neuer Ordner 2/node_modules/integer: Command failed.
Exit code: 127
Command: node tools/install
Arguments:
Directory: /Users/philippkuehn/Desktop/Neuer Ordner 2/node_modules/integer
Output:
/bin/sh: node-gyp: command not found
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this comm
```

And `better-sqlite3` fails too:

```
Philipps-MacBook-Pro:Neuer Ordner 3 philippkuehn$ yarn add --dev better-sqlite3
yarn add v1.3.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/2] ⠄ integer
[-/2] ⠄ waiting...
[-/2] ⠄ waiting...
[-/2] ⠄ waiting...
error /Users/philippkuehn/Desktop/Neuer Ordner 3/node_modules/integer: Command failed.
Exit code: 127
Command: node tools/install
Arguments:



```

Does it mean anything to you? 🤷‍♂️

**Comment by ryan-roemer** [comment]
Hmm... I was hoping one would hang and thus be our culprit. The packages failing aren't a big deal because they're optional.

I think at this point, we're hoping for more folks reporting a similar hanging issue or someone to identify other steps to help reproduce the issue so that we can actually see it in action...

**Comment by philippkuehn** [comment]
Hey, i fixed it with globally install node-gyp `npm install -g node-gyp`

**Comment by ajanes93** [comment]
I am also experiencing the same issue.  version 0.4.0 works fine.  Installing any version after just hangs as described above.  I am running yarn 1.3.2 and node 8.9.1

![screen shot 2017-11-17 at 09 20 55](https://user-images.githubusercontent.com/13524162/32939844-c8376a36-cb78-11e7-8fc6-3f8e1d78f4f4.png)
