### ISSUE TITLE
Doesn't seem to work with multiCompilers

### ISSUE THREAD

**Issue by Zephir77167** [FormidableLabs/webpack-dashboard#226]
> Please provide a description of the bug / issue, and provide the details below:

Hi,

I have a setup with two compilers (client and server), and webpack-dashboard doesn't seem to output any data when used on either of them.

====================================================================

###### If the issue is visual, please provide screenshots here

====================================================================

###### Steps to reproduce the problem

====================================================================

###### Please provide a gist of relevant files

1. package.json (specifically the script you are using to start the dashboard)

```
    "start:dev": "../../node_modules/.bin/webpack-dashboard -- node app.dev.js",
```

2. webpack.config.js

(not modified)

3. index.js (Your express based dev server, if applicable)

```
const express = require('express');
const bodyParser = require('body-parser');
const cookiesMiddleware = require('universal-cookie-express');
/* eslint-disable import/no-extraneous-dependencies */
const webpack = require('webpack');
const DashboardPlugin = require('webpack-dashboard/plugin');
const webpackDevMiddleware = require('webpack-dev-middleware');
const webpackHotMiddleware = require('webpack-hot-middleware');
const webpackHotServerMiddleware = require('webpack-hot-server-middleware');
/* eslint-enable import/no-extraneous-dependencies */
const clientConfig = require('./webpack.config.client');
const serverConfig = require('./webpack.config.server');

const PORT_NUMBER = process.env.PORT || 8080;
const app = express();

app.use(bodyParser.urlencoded({ extended: true }));
app.use(cookiesMiddleware());
app.use(express.static('public/assets'));

const multiCompiler = webpack([clientConfig, serverConfig]);
const clientCompiler = multiCompiler.compilers[0];

multiCompiler.apply(new DashboardPlugin({ port: PORT_NUMBER }));

app.use(webpackDevMiddleware(multiCompiler, {
  publicPath: clientConfig.output.publicPath,
  noInfo: true,
  stats: 'minimal',
}));
app.use(webpackHotMiddleware(clientCompiler));
app.use(webpackHotServerMiddleware(multiCompiler, {
  serverRendererOptions: { outputPath: clientConfig.output.path },
}));

app.listen(PORT_NUMBER, () => {
  // eslint-disable-next-line no-console
  console.log(`Server listening at port ${PORT_NUMBER}`);
});
```

====================================================================

###### More Details

- What operating system are you on? MacOS High Sierra 10.13.1
- What terminal application are you using? iTerm2
- What version of webpack-dashboard are you using? 1.0.2 (latest)
- What is the output of running `echo $TERM`? xterm-256color

Thanks in advance!

**Comment by ryan-roemer** [comment]
@Zephir77167 -- Can you package this up into a minimal repository with install + issue reproduction steps so we can jump in more quickly and see what the issue is? Thanks!

**Comment by Zephir77167** [comment]
Yes of course, sorry about the lack of information. I will set this up and come back to you!

**Comment by Zephir77167** [comment]
Here is a repo where my setup is reproduced : https://github.com/Zephir77167/ssr-starter-pack/tree/test/webpack-dashboard

I added `webpack-dashboard` to **app.dev.js**, and you can launch it with `yarn start:dev`.

Thanks in advance!

**Comment by ryan-roemer** [comment]
@Zephir77167 -- I've got your branch going, but it's hit an unrelated build error. The dashboard looks like it's providing normal info... Maybe fix that error and push an update and I'll check again?

![screen shot 2017-11-16 at 12 01 00 pm](https://user-images.githubusercontent.com/445557/32913090-1d5152f6-cac6-11e7-8469-7b7f6b9e3633.png)

**Comment by Zephir77167** [comment]
I am sorry for wasting your time, I have tested in a small terminal, and the dashboard was empty of any info... Tried in a large one and it worked!
