### ISSUE TITLE
Worker error Error: No code sections found

### ISSUE THREAD

**Issue by wellyshen** [FormidableLabs/webpack-dashboard#241]
Hi guys, I'm using this library (v1.1.1) and I upgraded to webpack v4 with babel 7. When I use the `babelrc: false` of babel-loader's option I encounter the following error: 

<img width="871" alt="2018-03-17 1 58 17" src="https://user-images.githubusercontent.com/21308003/37536981-226555ec-2987-11e8-9123-285296de02b4.png">

Here's the error snippet of my webpack config:
```javascript
// ...

      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'babel',
        options: {
          cacheDirectory: isDev,
          babelrc: false,  // <== Turn it off will cause the error
          presets: [
            ['@babel/preset-env', { modules: false, useBuiltIns: 'usage' }],
            '@babel/preset-react',
            '@babel/preset-stage-0',
            '@babel/preset-flow'
          ],
          plugins: [
            'react-hot-loader/babel',
            'loadable-components/babel',
            'lodash'
          ],
          env: { production: { plugins: ['transform-remove-console'] } }
        }
      },

// ...
```

You can reproduce this issue through [here](https://github.com/wellyshen/react-cool-starter/tree/webpack-4), any suggestion for it?

**Comment by ryan-roemer** [comment]
Can you review and https://github.com/FormidableLabs/webpack-dashboard/issues/234 and confirm if this is a duplicate or a different issue? Thanks.

**Comment by wellyshen** [comment]
@ryan-roemer This issue maybe related to [this comment] (https://github.com/FormidableLabs/webpack-dashboard/issues/234#issuecomment-369726623). Because I set up my babel-loader option the same with webpack v3, but this error only occurs in webpack v4.

**Comment by wellyshen** [comment]
@ryan-roemer Any update for this issue?

**Comment by ryan-roemer** [comment]
@wellyshen -- I'm working on a rewrite of `inspectpack` that is webpack4+ only and we'll transition to that for `webpack-dashboard` after that is completed.

If folks need something sooner, I'd be open to a PR in upstream `inspectpack` confirming + fixing this: https://github.com/FormidableLabs/inspectpack/issues/60 in the meantime which would bring back the code sections. (Summary: webpack yet again changed how code segments are are aggregated and our babel parsing in `inspectpack` needs to update).

**Comment by ryan-roemer** [comment]
Fixed in `webpack-dashboard@^2`-- the dashboard engine (`inspectpack`) now uses the webpack stats object for code introspection instead of parsing real outputted bundles.
