### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by LitileXueZha** [FormidableLabs/webpack-dashboard#253]
version of packages:
```
webpack: 4.12
webpack-dashboard: 2.0
webapck-dev-server: 3.1
```
run at windows 10's `cmd`.I have added `new DashboardPlugin()` into plugins array, but it seems to change nothing.

**Comment by ryan-roemer** [comment]
@LitileXueZha --  Can you provide a minimal repository with installation + error reproduction steps so we can hop in a win10 VM and see the error ourselves? Oh, and what terminal are you using (windows `cmd`?)?

Thanks!

**Comment by LitileXueZha** [comment]
@ryan-roemer Yes, i'm using windows 10 `cmd`.it doesn't throw errors and show dashboard.
Maybe you can install the packages which i list, and write a simple example.

Or can you provide a example which i can clone to local and try to run it?

**Comment by LitileXueZha** [comment]
@ryan-roemer Okay.Here is a example:<https://github.com/LitileXueZha/just-for-test.git>, it shows screenshot below when `npm start`.
![image](https://user-images.githubusercontent.com/22041474/42821902-361e242a-8a0c-11e8-9285-bb5d826d0a58.png)

**Comment by ryan-roemer** [comment]
You're not using the `webpack-dashboard` script to start things per the docs: https://github.com/FormidableLabs/webpack-dashboard#use

Change this up to:

```diff
diff --git a/package.json b/package.json
index 3377272..3fea07a 100644
--- a/package.json
+++ b/package.json
@@ -5,7 +5,7 @@
   "main": "index.js",
   "scripts": {
     "test": "echo \"Error: no test specified\" && exit 1",
-    "start": "webpack-dev-server"
+    "start": "webpack-dashboard -- webpack-dev-server"
   },
   "repository": {
     "type": "git",
```

and everything should work!
