### ISSUE TITLE
Can I use the webpack dashbord from node?

### ISSUE THREAD

**Issue by canda** [FormidableLabs/webpack-dashboard#259]
Is it possible/the intended way of use to run this library from node instead of the cli?

I wanted to bundle a webpack builder with the config we share across.
I figured I should run webpack from node (inside my webpack builder library) instead of the cli to avoid dependencies issues.
And I wanted bundle the webpack dashboard with this builder library.

**Comment by parkerziegler** [comment]
cc/ @ryan-roemer Could you weigh in here? From what I understand, you can use `compiler.apply` in a Node script to apply the `DashboardPlugin` directly. Check out the example here and let me know if it suits your use case: https://webpack.js.org/concepts/plugins/#node-api

**Comment by ryan-roemer** [comment]
@parkerziegler @canda -- This is on my list, but I'm a bit backlogged these days. 🙏

**Comment by canda** [comment]
No hurries.
I don't quite understand why you decoupled the dashboard process from the
webpack process? What was the purpose there?
For my use case being a preconfigured webpack library to build your
application, I think I want to include this dashboard in the same process
so that the user just run my library's main script and see the magic
happens on his cli.

**Comment by ryan-roemer** [comment]
For "why decoupled", @kenwheeler knows for sure.

I can research the technical constraints after the fact, but I'm guessing the main constraint is that blessed can't just take over a terminal from within a webpack plugin -- a separate process needs to do that, from which inside you can then run webpack commands. Hence, the split between the `webpack-dashboard` CLI and the webpack plugin which then communicate over IPC.

**Comment by ryan-roemer** [comment]
Hi folks! Turns out we had examples all along here: https://github.com/FormidableLabs/webpack-dashboard/blob/master/docs/getting-started.md#use-the-new-way 😂 

_and_ an official explanation of the architecture:

> After the initial release, it was decided that running a separate process and communicating via sockets would be more efficient and solves a lot of problems with stdout.

I'm closing, but let me know if there's anything that's not working or needs more guidance. Thanks!
