### ISSUE TITLE
Infrastructure: Update to `inspectpack@4`.

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/webpack-dashboard#261]
`inspectpack@4` is a major release. Task

- [x] Update to `inspectpack@4`
- [x] Note the [change log](https://github.com/FormidableLabs/inspectpack/blob/master/HISTORY.md#400) and fix any breaking changes.
- [ ] Consider potential UI improvements.

/cc @parkerziegler @ElreyB (for whatever triage you feel like! no rush!)

**Comment by parkerziegler** [comment]
Thanks @ryan-roemer, @ElreyB and I will do some pair programming together this week to try and land this. Any suggestions on potential UI improvements?

**Comment by ryan-roemer** [comment]
Offhand, maybe something like:

### Use new version `ranges`

https://github.com/FormidableLabs/webpack-dashboard/blob/master/utils/format-versions.js#L5-L9

```js
// From inspectpack.
const pkgNamePath = pkgParts => pkgParts.reduce(
  (m, part) => `${m}${m ? " -> " : ""}{cyan-fg}${part.name}{/}@${part.version}`,
  ""
);
```

could take advantage of the neater, newer `range` (using semver range instead of installed version) like here:

https://github.com/FormidableLabs/inspectpack/blob/master/src/plugin/duplicates.ts#L71-L75

```ts
// `duplicates-cjs@1.2.3 -> different-foo@1.1.1 -> foo@3.3.3`
const pkgNamePath = (pkgParts: INpmPackageBase[]) => pkgParts.reduce(
  (m, part) => `${m}${m ? " -> " : ""}${part.name}@${part.range}`,
  "",
);
```

**Important note**: Don't use `chalk` formatting for `webpack-dashboard`. We have to use the blessed colorings (otherwise alignment gets all messed up for the terminal windows).

### Update versions

The `versions` action had the most reworking (including some major changes), so https://github.com/FormidableLabs/webpack-dashboard/blob/master/utils/format-versions.js needs the most critical eye.

### Other?

Maybe review the UI and see if anything needs better colors, or if there are any output questions we could do better? Happy to chat!
