### ISSUE TITLE
[RESEARCH] Send SIGINT on Ctrl+C instead of immediate exit (?)

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/webpack-dashboard#272]
`dashboard/index.js` exits process same as `nodejs-dashboard`. Over there, this PR was opened https://github.com/FormidableLabs/nodejs-dashboard/pull/93 suggesting a more nuanced way to exit.

Maybe consider here too?

I'm also curious if it impacts some of `Ctrl-SOMETHING` issues on this project...

/cc @parkerziegler

**Comment by parkerziegler** [comment]
Thanks for opening this @ryan-roemer, I'll test this out this afternoon / weekend.

**Comment by parkerziegler** [comment]
@ryan-roemer I tested this locally and confirmed that it works on latest macOS. I really wish we had a Windows machine so we could test this (don't really want to spin up VirtualBox for this), but it is in the source of `neo-blessed` as well: https://github.com/embark-framework/neo-blessed/blob/master/lib/widgets/screen.js#L225-L235. Overall I'd be comfortable making this change!

**Comment by ryan-roemer** [comment]
![](https://i.stack.imgur.com/MNeE7.jpg)

**Comment by parkerziegler** [comment]
Closed by #277.
