### ISSUE TITLE
Issue while running tail -f command 

### ISSUE THREAD

**Issue by srirama-rayaprolu** [FormidableLabs/webpack-dashboard#273]
While the tail -f command is command is running in the git bash terminal and hit the enter button 6 to 7 times
and entered some other command with out pressing the Ctrl-C. 

At this point on pressing Ctrl-C, then behavior is not similar to putty. 

In putty the new lines are not buffered.

Below is the screenshot from the Git-Bash windows terminal, 

![image](https://user-images.githubusercontent.com/4252136/53637660-c2345700-3c49-11e9-9542-285e103cb9d3.png)

How can I control this behavior? any configuration changes?

My use case is while tailing the log files, we may hit the enter button multiple times for segregation purpose. But these lines are buffered in the terminal and the moment we hit the Ctrl-C, the control will scroll for that many times as shown above. This kind of behavior not observed in Putty.

###### More Details

- Windows 10
- Git Bash
- latest
- xterm

**Comment by srirama-rayaprolu** [comment]
![image](https://user-images.githubusercontent.com/4252136/53637417-1db21500-3c49-11e9-93b7-6dcf813128d0.png)

**Comment by parkerziegler** [comment]
@srirama-rayaprolu thanks for opening this issue.

I'm a little confused by the behavior you're describing. I'm not sure there's much of anything `webpack-dashboard` can do for you in this case, as it sounds like you're having different experiences across environments (i.e. Git Bash vs. PuTTY). It may be worth checking the issues for the rendering library we use to take over the terminal, [`neo-blessed`](https://github.com/embark-framework/neo-blessed), as this handles most of the command line interactions for us. Sorry we can't be of more help, but I think this is beyond the purview of this library. Best of luck!

**Comment by srirama-rayaprolu** [comment]
https://github.com/mintty/mintty/issues/805
