### ISSUE TITLE
Is it not supported in Windows 8 cmd ?

### ISSUE THREAD

**Issue by gaurav5430** [FormidableLabs/webpack-dashboard#274]
> Please provide a description of the bug / issue, and provide the details below:

Trying to make this work in Windows 8.
I can see the official documentation says that the Windows 10 is supported and cmd is supported.
Just wanted to get a clarification whether Windows 8 is not supported at all ?
====================================================================

###### If the issue is visual, please provide screenshots here

====================================================================

###### Steps to reproduce the problem

====================================================================

###### Please provide a gist of relevant files

1. package.json (specifically the script you are using to start the dashboard)
2. webpack.config.js
3. index.js (Your express based dev server, if applicable)

====================================================================

###### More Details

- What operating system are you on? Windows 8
- What terminal application are you using? CMD
- What version of webpack-dashboard are you using? ^3.0.0
- What is the output of running `echo $TERM`?

**Comment by parkerziegler** [comment]
Hey @gaurav5430, thanks for checking in. I'm not 100% sure of the Windows 8 compatibility – I haven't tested it, and don't have easy access to a machine. I can see if someone else here at Formidable does or if it's possible to spin up a VM. A few other things that could be causing issues:

1. What version of Node are you running? As of ^3.0.0, `webpack-dashboard` requires Node > 8. See the migration instructions here: https://github.com/FormidableLabs/webpack-dashboard/releases.
2. What is the script you're using to start the dashboard (your `start` script in `package.json`)? What output do you get, if any, when running it?

If you can send me the above, along with a repo I can clone to reproduce the issue, I'd be happy to help! Thanks again.

**Comment by parkerziegler** [comment]
@gaurav5430 closing this issue for now as we're only planning to support Windows 10 and up.
