### ISSUE TITLE
Doesn't got to `Status: Success

### ISSUE THREAD

**Issue by westbrook-asapp** [FormidableLabs/webpack-dashboard#278]
> Please provide a description of the bug / issue, and provide the details below:

====================================================================

###### If the issue is visual, please provide screenshots here

====================================================================

###### Steps to reproduce the problem

====================================================================

###### Please provide a gist of relevant files

1. package.json (specifically the script you are using to start the dashboard)
2. webpack.config.js
3. index.js (Your express based dev server, if applicable)

====================================================================

###### More Details

- What operating system are you on?
- What terminal application are you using?
- What version of webpack-dashboard are you using?
- What is the output of running `echo $TERM`?

**Comment by parkerziegler** [comment]
@westbrook-asapp is it safe to assume that #279 captures this issue and we can close this one?

**Comment by westbrook-asapp** [comment]
Ooops, didn't realize this double posted. Sorry about that.
