### ISSUE TITLE
Bug: Straight webpack build (without watch) does not reach final state.

### ISSUE THREAD

**Issue by humorHan** [FormidableLabs/webpack-dashboard#294]
![image](https://user-images.githubusercontent.com/10398024/63837145-7de20380-c9ad-11e9-8acb-d3fb3660bfc5.png)

**Comment by humorHan** [comment]
always loading，because of the use of `lerna`？

**Comment by yinshanyang** [comment]
I had a similar issue on `3.1.0` whilst programmatically calling `webpack-dashboard` (instead of the cli)

I have found that changing:
```
new DashboardPlugin(dashboard.setData)
```

to this:
```
new DashboardPlugin({ handler: dashboard.setData })
```

resolved the issue for me.

**Comment by tanrich** [comment]
@ryan-roemer Hello. I have the same problem. Is there a solution?

**Comment by tanrich** [comment]
> @ryan-roemer Hello. I have the same problem. Is there a solution?

I found that downgrading to 3.0.7 is good.The latest version still has the problem.

**Comment by ryan-roemer** [comment]
@tanrich I'm happy to jump in and diagnose if there's a reproduction. Can you make a minimal GitHub repository with installation instructions and instructions of the commands you are running in the terminal with `webpack-dashboard` so that we can pull the repo and see what you are experiencing firsthand?

**Comment by peterhpchen** [comment]
I had a similar issue on `3.3.3`. After I downgraded to `3.2.1`, it works fine.

Code: https://github.com/peterhpchen/book-webpack-examples/tree/develop/v4/27-production-analyze/dashboard-demo (It has issue after upgrade to `3.3.3`)

Thank you.

**Comment by ryan-roemer** [comment]
Thanks @peterhpchen ! Verified issue reproduction with your project. We'll dig in from here now that we have a repro.

Notes: From `yarn build` with this `package.json`:

```js
  "scripts": {
    "build": "webpack-dashboard -- webpack"
  },
  "devDependencies": {
    "webpack": "^4.44.2",
    "webpack-cli": "^3.3.12",
    "webpack-dashboard": "^3.3.3"
  }
```

we get:

![Screen Shot 2021-07-10 at 1 13 33 PM](https://user-images.githubusercontent.com/445557/125175414-c8736000-e180-11eb-98c1-9873c9b09563.png)

**Comment by ryan-roemer** [comment]
On npm linking latest master I now get the `(loading...)` thing. Weird. At any rate, I'll keep digging...


![Screen Shot 2021-07-10 at 1 20 30 PM](https://user-images.githubusercontent.com/445557/125175531-b219d400-e181-11eb-881d-4cd22401c8fb.png)

**Comment by peterhpchen** [comment]
Thanks, @ryan-roemer .

Just a reminder that webpack v5 has the same issue in `3.3.3`.

Thank you.

**Comment by ryan-roemer** [comment]
@peterhpchen -- On further inspection, one issue I'm noticing in the repo is that it's doing `webpack` and not `webpack --watch` or `webpack-dev-server`, which is just a single build and not something persistent.

I'm still going to investigate, but the following works just fine for `yarn build`:

```diff
diff --git a/v4/27-production-analyze/dashboard-demo/package.json b/v4/27-production-analyze/dashboard-demo/package.json
index 5963133..5139015 100644
--- a/v4/27-production-analyze/dashboard-demo/package.json
+++ b/v4/27-production-analyze/dashboard-demo/package.json
@@ -4,11 +4,11 @@
   "main": "index.js",
   "license": "MIT",
   "scripts": {
-    "build": "webpack-dashboard -- webpack"
+    "build": "webpack-dashboard -- webpack --watch"
   },
   "devDependencies": {
     "webpack": "^4.44.2",
     "webpack-cli": "^3.3.12",
-    "webpack-dashboard": "^3.2.1"
+    "webpack-dashboard": "^3.3.3"
   }
 }
```
