### ISSUE TITLE
 The module of the dashboard is always loading;  

### ISSUE THREAD

**Issue by yaolidd01** [FormidableLabs/webpack-dashboard#298]
Every time I start a build, May lack any dependencies.  The module of the dashboard is always loading;  After about half an hour, it is still loading state.

**Comment by yaolidd01** [comment]
![image](https://user-images.githubusercontent.com/48903073/66975189-50bdf180-f0d0-11e9-81cb-5a253345fd1d.png)

**Comment by yaolidd01** [comment]
my webpack config:

**Comment by ryan-roemer** [comment]
Maybe try:

```js
const DashboardPlugin = require('webpack-dashboard/plugin')
// ...
plugins : [
  new DashboardPlugin(),
]
```

If that doesn't help steer you in the right direction, can you please open a minimal GitHub repository or a CodeSandbox with install + build + error reproduction steps so that someone from our team can pull down and reproduce exactly what you're seeing? Thanks!

**Comment by yaolidd01** [comment]
> Maybe try:
> 
> ```js
> const DashboardPlugin = require('webpack-dashboard/plugin')
> // ...
> plugins : [
>   new DashboardPlugin(),
> ]
> ```
> 
> If that doesn't help steer you in the right direction, can you please open a minimal GitHub repository or a CodeSandbox with install + build + error reproduction steps so that someone from our team can pull down and reproduce exactly what you're seeing? T

**Comment by yaolidd01** [comment]
> Maybe try:
> 
> ```js
> const DashboardPlugin = require('webpack-dashboard/plugin')
> // ...
> plugins : [
>   new DashboardPlugin(),
> ]
> ```
> 
> If that doesn't help steer you in the right direction, can you please open a minimal GitHub repository or a CodeSandbox with install + build + error reproduction steps so that someone from our team can pull down and reproduce exactly what you're seeing? Thanks!

[here](https://github.com/yaolidd01/test-webpack)

**Comment by ryan-roemer** [comment]
Thanks for the repository. The adjustment I suggested works for me. Try this diff:

```diff
diff --git a/build/plugins.js b/build/plugins.js
index 046f9fd..33cec62 100644
--- a/build/plugins.js
+++ b/build/plugins.js
@@ -17,10 +17,7 @@ const MomentLocalesPlugin = require('moment-locales-webpack-plugin')
 const { compilerHooks } = require('./custom-plugins')
 const constants = require("./const");
 const { assetsPath } = require("./utils");
-const Dashboard = require('webpack-dashboard');
 const DashboardPlugin = require('webpack-dashboard/plugin')
-const dashboard = new Dashboard();
-
 
 const basePlugins = [
        new webpack.DefinePlugin({
@@ -54,7 +51,7 @@ const devPlugins = [
        ...compilerHooks,
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NamedModulesPlugin(), // 执行热替换时打印模块名字
-       new DashboardPlugin(dashboard.setData),
+       new DashboardPlugin(),
 ];
 
 const prodPlugins = [
diff --git a/package.json b/package.json
index d46e145..dc320c9 100644
--- a/package.json
+++ b/package.json
@@ -10,6 +10,9 @@
     }
   },
   "license": "MIT",
+  "scripts": {
+    "start": "webpack-dashboard -- webpack"
+  },
   "devDependencies": {
     "@babel/core": "^7.6.4",
     "@babel/plugin-proposal-class-properties": "^7.5.5",

```

Then run `yarn start` and I get:

![Screen Shot 2019-10-16 at 9 25 55 PM](https://user-images.githubusercontent.com/445557/66977668-ac01cc80-f05b-11e9-8fc4-0d88e04cb7d5.png)
