### ISSUE TITLE
Can't resize interface while webpack is doing synchronous work

### ISSUE THREAD

**Issue by graingert** [FormidableLabs/webpack-dashboard#30]
Maybe webpack should be run in another process, with a dashboard producer plugin that sends log data down a socket for the dashboard UI and consumer to parse and display?

**Comment by kenwheeler** [comment]
how would you go about doing that? in general?

**Comment by graingert** [comment]
Spawn a subprocess with webpack in and use a socket to communicate

This package wraps all this for you in a postMessage API:
https://www.npmjs.com/package/webworker-threads

**Comment by kenwheeler** [comment]
That sounds pretty cool, I'll check that out

**Comment by kenwheeler** [comment]
@graingert I got started, but it looks like because i'm using express, that spawns a new process for dev server, so I lose process.send.

https://github.com/FormidableLabs/webpack-dashboard/tree/separate-processes

How does a unix socket work? I feel like if I run `webpack-dev-server -- nodemon index.js`, thats like 3 processes down, and process.env stuff won't get picked up. What's a more global option?

**Comment by graingert** [comment]
Yeah so you create a temporary directory and  choose a path inside that
directory and pass it to
https://nodejs.org/api/net.html#net_server_listen_path_backlog_callback you
could also use a TCP socket with a random port.

You just need to connect to the same socket in your plugin by passing the
socket connection details in an environment variable or something

On 16 Aug 2016 23:41, "Ken Wheeler" <notifications@github.com> wrote:

@graingert <https://github.com/graingert> I got started, but it looks like
because i'm using express, that spawns a new process for dev server, so I
lose process.send.

https://github.com/FormidableLabs/webpack-dashboard/tree/separate-processes

How does a unix socket work? I feel like if I run webpack-dev-server --
nodemon index.js, thats like 3 processes down, and process.env stuff won't
get picked up. What's a more global option?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/FormidableLabs/webpack-dashboard/issues/30#issuecomment-240261934>,
or mute the thread

**Comment by kenwheeler** [comment]
This should do it, eh? https://github.com/FormidableLabs/webpack-dashboard/pull/50

**Comment by exogen** [comment]
Think this can be closed but want to confirm /cc @kenwheeler @graingert
