### ISSUE TITLE
Webpack 5 warning message conflict

### ISSUE THREAD

**Issue by sourena2575** [FormidableLabs/webpack-dashboard#314]
> Please provide a description of the bug / issue, and provide the details below:

In webpack 5 after compilning webpack web dashbord replace all warning messages with custom messages but in new webpack release this messagse is type of object and not string therefore dev server would crash

**Comment by ryan-roemer** [comment]
Update: I've hit this in my current branch for webpack5 support and think I have a straightforward path to handle old + new webpack formats.

**Comment by ryan-roemer** [comment]
@sourena2575 Can you confirm that `webpack-dashboard@3.3.0` has fixed the issue you've identified? Thanks!
