### ISSUE TITLE
How to make it work if server-side-rendering is enabled?

### ISSUE THREAD

**Issue by mocheng** [FormidableLabs/webpack-dashboard#32]
In my single page application, server-side-rendering is enabled. So, react component is rendered in server side and generated HTML markup is returned to browser side. After this, UI update caused by user interaction is rendered in browser side since it is a single page application.

The problem is that I cannot make `webpack-dashboard` work appropriately if server-side-rendering is enabled. Say, some typo during development makes the compliation fail. The dashboard can show it, but at the same time the server-side would also detects the syntax error and dump error message. It would flush the dashboard output. 

The section in **Turn off Errors** only applies for webpack build, it doesn't cover server-side-rendeirng.

If I tried to silence server output by `&>/dev/null`, but it makes dashboard disappear too.

Any idea how to make it work if server-side-rendering is enabled?

**Comment by kenwheeler** [comment]
This will be fixed by #27

**Comment by kenwheeler** [comment]
I'm going to close this in favor of continuing discussiong in #12
