### ISSUE TITLE
Bug: "Success" status overwritten and stuck in "Compiling" for finished webpack build.

### ISSUE THREAD

**Issue by SoxPan** [FormidableLabs/webpack-dashboard#321]
> Please provide a description of the bug / issue, and provide the details below:

Progress is 100% but status is still Compiling

###### If the issue is visual, please provide screenshots here
<img width="844" alt="Screen Shot 2021-01-25 at 9 14 31 PM" src="https://user-images.githubusercontent.com/16606566/105740135-52709900-5f52-11eb-8fa4-5365ec3089f4.png">
====================================================================

###### Steps to reproduce the problem

Just running `webpack-dashboard --minimal -- webpack --config webpack.config.js` command

###### Please provide a gist of relevant files

1. https://gist.github.com/SoxPan/138cec681ab71e2219f60468c5b58dcb
2. https://gist.github.com/SoxPan/6e064d6d7ee301497d734e56b475c4b7

###### More Details

- What operating system are you on? MacOS Big Sur
- What terminal application are you using? MacOS Terminal
- What version of webpack-dashboard are you using? 3.3.0
- What is the output of running `echo $TERM`? xterm-256color

**Comment by ryan-roemer** [comment]
Hi! Some quick questions to help us diagnose:

- Did this command work with versions prior to `3.3.0`?
- Does the command work without the `--minimal` flag?

And if possible, could you put together a minimal repository that exhibits the problem? (If we have something we can pull down and run it's way faster for us to diagnose issues).

Thanks!

**Comment by ryan-roemer** [comment]
Confirmed. At least in webpack5 there's some incorrect interplay with `webpack.ProgressPlugin` reporting more status _after_ `hooks.done` fires. Debug logs:

```
TODO webpack.ProgressPlugin  status: 'Compiling', percent: 0.95, msg: 'emitting' 
TODO webpack.ProgressPlugin  status: 'Compiling', percent: 0.98, msg: 'emitting' 
TODO webpack.ProgressPlugin  status: 'Compiling', percent: 0.98, msg: 'emitting' 
TODO webpack.ProgressPlugin  status: 'Compiling', percent: 0.99, msg: 'done'     
TODO webpack.ProgressPlugin  status: 'Compiling', percent: 0.99, msg: 'done'     
TODO hook.done  status: 'Success'         
# ... webpack stuff snipped ...                                       
TODO webpack.ProgressPlugin  status: 'Compiling', percent: 0.99, msg: 'done'     
TODO webpack.ProgressPlugin  status: 'Compiling', percent: 0.99, msg: ''         
TODO webpack.ProgressPlugin  status: 'Compiling', percent: 0.99, msg: 'cache' 
TODO webpack.ProgressPlugin  status: 'Compiling', percent: 0.99, msg: 'cache' 
TODO webpack.ProgressPlugin  status: 'Compiling', percent: 0.99, msg: 'cache' 
TODO webpack.ProgressPlugin  status: 'Compiling', percent: 0.99, msg: 'cache' 
TODO webpack.ProgressPlugin  status: 'Compiling', percent: 1, msg: ''         
```

We can probably use some threshold of `percent` and/or just straight `msg` to special case not having `ProgressPlugin` overwrite a `Success` (or possibly other) status.
