### ISSUE TITLE
webpack-dashboard: clear pipeline warnings

### ISSUE THREAD

**Issue by acharyakavita** [FormidableLabs/webpack-dashboard#358]
This project currently has node version warnings in the CICD pipeline logs. This is likely due to using an old version of the below actions. 
        Try and convert to the newest version.
        - actions/checkout → actions/checkout@v4
        - actions/setup-node → actions/setup-node@v4
        - pnpm/action-setup → pnpm/action-setup@v3
        - actions/cache → actions/cache@v4
        - actions/stale → actions/stale@v4 
        In order to conform with Nearform_Commerce OSS standards, please convert to use newer versions which no longer have the warning.

        created by Sawyer Automation Bot © using github cli

**Comment by Mati882023** [comment]
> This project currently has node version warnings in the CICD pipeline logs. This is likely due to using an old version of the below actions. 
>         Try and convert to the newest version.
>         - actions/checkout → actions/checkout@v4
>         - actions/setup-node → actions/setup-node@v4
>         - pnpm/action-setup → pnpm/action-setup@v3
>         - actions/cache → actions/cache@v4
>         - actions/stale → actions/stale@v4 
>         In order to conform with Nearform_Commerce OSS standards, please convert to use newer versions which no longer have the warning.
> 
>         created by Sawyer Automation Bot © using github cli
