### ISSUE TITLE
Namespaced modules aren't showing up properly

### ISSUE THREAD

**Issue by iDuuck** [FormidableLabs/webpack-dashboard#38]
Have a look at this screenshot: It is a public namespaced module that I published. After installation only the @iduuck was shown. It's normally `@iduuck/react-phone-input`.

![screen shot 2016-08-16 at 4 59 41 pm](https://cloud.githubusercontent.com/assets/325241/17703710/fc81aaf4-63d2-11e6-941b-622649202184.png)

**Comment by kenwheeler** [comment]
Whoah, great catch

**Comment by iDuuck** [comment]
Also, I don't know if this is related or possible to implement, but for example when I require/import submodules like `lodash/merge` or something like this, `lodash` is still written as a single dependency and not what space `lodash/merge` is taking.

**Comment by iDuuck** [comment]
@kenwheeler Just added a pull request, tested this locally and worked for me, but please be sure to test before merging (what about a test suite for the project)
