### ISSUE TITLE
Read stdout for simpler config

### ISSUE THREAD

**Issue by JaKXz** [FormidableLabs/webpack-dashboard#39]
It would be really nice if I could simply pipe my existing webpack/webpack-dev-server command:

`webpack-dev-server --hot --progress | webpack-dashboard` and so on. 

Apologies if this has been suggested already, I'm on my phone and there's no search.

**Comment by jamesbvaughan** [comment]
This would be awesome for use in larger orgs/projects where not everyone is down to use webpack-dashboard.

**Comment by kenwheeler** [comment]
This should be fixed in the latest release
