### ISSUE TITLE
Why terminal?

### ISSUE THREAD

**Issue by wavebeem** [FormidableLabs/webpack-dashboard#40]
Why use the terminal for this? Something like an Electron app would have much more freedom with regards to interaction and display of information.

**Comment by kenwheeler** [comment]
because the terminal is fun.

**Comment by wavebeem** [comment]
If that's what makes you happy, cool. I'm just saying that with a web app you could easily make [links that open your code](https://www.npmjs.com/package/open-in-editor), as well as allow scrolling and whatnot. Anyway, it looks like a cool project otherwise. Have fun!

**Comment by kenwheeler** [comment]
scrolling works, but i really just wrote this initially for fun. an electron app is definitely worth exploring though.
