### ISSUE TITLE
Powershell doesn't render borders properly

### ISSUE THREAD

**Issue by kaeedo** [FormidableLabs/webpack-dashboard#41]
Trying to use this in powershell, but it doesn't render the borders properly. It works fine in command prompt. 

![cmd](https://cloud.githubusercontent.com/assets/3847895/17713906/95655a3e-63fd-11e6-8127-7b6c3b9fc566.png)
![powershell](https://cloud.githubusercontent.com/assets/3847895/17713907/957b604a-63fd-11e6-85bd-d06d9f2b5602.png)

Awesome tool btw

**Comment by kenwheeler** [comment]
Lets continue in #43
