### ISSUE TITLE
interferes with npm-check?

### ISSUE THREAD

**Issue by eikaramba** [FormidableLabs/webpack-dashboard#42]
I was executing **npm-check** (https://github.com/dylang/npm-check) today (library to update your npm dependencies). And somehow webpack-dashboard is showing up when i do that. I guess it is somehow called or interfering. Anyhow, i can scroll trhough the entries but not hit space to select them anymore.

Maybe someone can confirm this behaviour but i did not do anything fancy and webpack-dashboard is only configured in the webpack.config.js so it should not be because of that.

**Comment by christopherthielen** [comment]
I noticed that the dashboard is drawn when you call `new Dashboard()` even if you don't create an instance of the plugin. I wrapped the initialization code in conditionals (I only want it when I'm using dev server).  

```js
const IS_DEV_SERVER = process.argv[1].indexOf('webpack-dev-server') >= 0;

if (IS_DEV_SERVER) {
  Dashboard = require('webpack-dashboard');
  DashboardPlugin = require('webpack-dashboard/plugin');
  dashboard = new Dashboard();
}```

Perhaps you're seeing something similar?

**Comment by eikaramba** [comment]
hey @christopherthielen , that did the trick! :=) just needed to initialize the variables, but apart from that now it is working. strange that npm-check is actually somehow calling/using webpack.config.js.
