### ISSUE TITLE
Colors aren't parsed properly on Windows?

### ISSUE THREAD

**Issue by jedmao** [FormidableLabs/webpack-dashboard#43]
It looks like the color codes aren't being parsed properly, but I'm not sure. This is what it looks like on Windows 10 Command Prompt for me:

![image](https://cloud.githubusercontent.com/assets/1058243/17719189/57d9e546-63de-11e6-9cbe-a7d6d262b0ab.png)

It's even worse on Git Bash for Windows. 99% of the screen is black and these characters race across the screen.

**Comment by kenwheeler** [comment]
That looks rough. Looking into it.

**Comment by danielverejan** [comment]
Works great for me on windows(cmd, powershell), no Git Bash support and scroll and resize.
![2016-08-17_0945](https://cloud.githubusercontent.com/assets/7072732/17727084/8f81abd8-645f-11e6-9ef8-5be3f20ea1ba.png)

**Comment by jedmao** [comment]
PowerShell is broken too, see?

![image](https://cloud.githubusercontent.com/assets/1058243/17727824/5c7d615c-6421-11e6-9456-6f822a890844.png)

**Comment by jedmao** [comment]
Just upgraded from Node 6.3.1 to 6.4.0. Same problem, even though the project warnings are gone.

**Comment by danielverejan** [comment]
Works for me in Powershell, checked with node 5.12.0 and latest on windows 10 1511. 
Also it behaves the best on window resize, the UI remains the same as at the start.

**Comment by jedmao** [comment]
@danielverejan can you elaborate on the terminal option? Not sure what that is.

**Comment by danielverejan** [comment]
index.js from node_modules/webpack-dashboard/dashboard/
there you can use "terminal" option later used in blessed.
![2016-08-17_1133](https://cloud.githubusercontent.com/assets/7072732/17729827/abd8208c-646e-11e6-8080-e0eac7d98926.png)

also just noticed that with node 6.3.1 resize works well in cmd.

**Comment by austinsc** [comment]
To clarify- the options object that is being passed to blessed.screen() needs to look like this:
```
this.screen = blessed.screen({
    smartCSR: true,
    title: 'reactotron',
    dockBorders: false,
    fullUnicode: true,
    autoPadding: true,
    terminal: 'windows-ansi'
  });
```

**Comment by kenwheeler** [comment]
@austinsc shouldn't that get set automatically? the `windows-ansi` part?

**Comment by jedmao** [comment]
I know @danielverejan said NOT to use the `terminal` option, but since I hadn't touched it, I set it to `terminal: 'windows-ansi'` just to see what happens and sure enough, that fixed it in both Windows 10 Command Prompt as well as PowerShell!

That's not an ideal solution, however, so I looked deeper and it turns out I can just set my `TERM` environment variable to `windows-ansi` w/o touching `/node_modules/webpack-dashboard/dashboard/index.js` and that works too!

Note: Still haven't found a fix for Git Bash (tried `ansi` and `msys`).

**Comment by danielverejan** [comment]
That's probably because it's an emulator? Tried different options for Git Bash and terminal option like xterm, xterm-256color but still without success.

**Comment by jedmao** [comment]
@danielverejan, yeah. I tried those too. I can definitely use Windows Command Prompt though.

**Comment by smrq** [comment]
I had this issue using Cmder.  It's probably because of some misconfiguration in Cmder itself, but setting `TERM=windows-ansi` fixed it.

**Comment by joyfulelement** [comment]
Had the same display issue with the **`Cmder`** on Windows 2012. 
The environment variable was `TERM=cygwin`, confirmed by changing it to `TERM=windows-ansi` would fix the issue.

### With Cmder
When the environment variable was `TERM=cygwin`:
![image](https://cloud.githubusercontent.com/assets/5963818/17783721/3b24dad6-6547-11e6-90ce-703ba649d812.png)

### The Fix
You can change the environment variable via Cmder's setting page as follow:

![image](https://cloud.githubusercontent.com/assets/5963818/17783849/ea2e4ba2-6547-11e6-9633-9589b1d6b638.png)

### The Fixed Display
After changing the environment variable to `TERM=windows-ansi`, the display would be fixed.

![image](https://cloud.githubusercontent.com/assets/5963818/17783886/16cc6a72-6548-11e6-8398-590088ddce74.png)

**Comment by kenwheeler** [comment]
This should be all set now. Can someone familiar with the process PR a note to the README on the best way to get this fix going?

**Comment by danielverejan** [comment]
I think the best way to fix this is to whitelist(for windows should be enough) the supported terminals before screen initialization. Blessed already performs a check for that
`this._terminal = options.terminal
    || options.term
    || process.env.TERM
    || (process.platform === 'win32' ? 'windows-ansi' : 'xterm');` but checks the platform in the end.

**Comment by jedmao** [comment]
@danielverejan that's odd, because if they did the `win32` check at the end then I wouldn't need to do set my ENV variable to fix it. I need to look into this more.

**Comment by jedmao** [comment]
For the record, it looks like @danielverejan is referencing [these lines](https://github.com/chjj/blessed/blob/62b439ef8eaa7db9b85e32fa718f1c802f893b24/lib/program.js#L69-L72). If setting `windows-ansi` is not working properly there, maybe it's a Blessed issue and we can move the issue there; thus, not requiring anybody to fudge w/ their environment variables. That would be ideal.
