### ISSUE TITLE
Improve instructions for beginners?

### ISSUE THREAD

**Issue by typeshige** [FormidableLabs/webpack-dashboard#44]
I tried to follow the instructions but I'm not yet experienced enough to know what files I should be editing. 

Could this be improved and perhaps a simple example added so folks can get to a running example right away?

Thanks.

**Comment by kenwheeler** [comment]
I'm in the process of making this even easier. Ideally the API will be just running `webpack-dashboard -- node index.js`

**Comment by DrakeLeung** [comment]
Just add a few lines code:

```javascript
// webpack.config.js

const Dashboard = require('webpack-dashboard');
const DashboardPlugin = require('webpack-dashboard/plugin');
const dashboard = new Dashboard();

module.exports = {
  plugins: [
    new DashboardPlugin(dashboard.setData),
  ],

  devServer: {
    quiet: true, // it seems work without this 
  },
}
```

There is a [gist](https://gist.github.com/DrakeLeung/b409199831daf22fa9cac36a2752c041) of the completed config of webpack if you wanna check.

**Comment by ESWAT** [comment]
@DrakeLeung I’ve found that setting `quiet: true` in the devServer config doesn’t actually do anything. You have to set it in in the constructor as per the README file. Perhaps you had it set in the constructor hence why setting it in the config file doesn’t do anything for you.

**Comment by kenwheeler** [comment]
This should simplify things https://github.com/FormidableLabs/webpack-dashboard/pull/50

**Comment by typeshige** [comment]
Thanks @DrakeLeung!  This helped out a lot!!

**Comment by typeshige** [comment]
I'm not sure where to put the constructor and on the README, the unclosed "(" at the end is throwing me off, but I think I'm close to having this up and running!

**Comment by kenwheeler** [comment]
This should be fixed in the latest release
