### ISSUE TITLE
Unable to select logs to copy/paste

### ISSUE THREAD

**Issue by vipulnsward** [FormidableLabs/webpack-dashboard#45]
I am unable to select logs to copy/paste, etc.
Currently using: iTerm2

**Comment by kenwheeler** [comment]
That might be a limitation of blessed, but i'd love to get it sorted out

**Comment by jasonwilson** [comment]
Looks like there's iterm clipboard support through a special interface Might be worth checking out https://github.com/chjj/blessed/issues/159 @kenwheeler

**Comment by mgan59** [comment]
Yeah, would be nice to copy/paste build errors from the dashboard into slack, not a fan of having to screenshot and dump into the engineering channel.

**Comment by akinnee** [comment]
Great job on the dashboard. I'd love to see this work as well.

**Comment by Nizam-Ahamed** [comment]
nefahamed@gmail.com

**Comment by creatifyme** [comment]
Any update on this?

**Comment by austinfox** [comment]
Any update? I'm using iTerm2 and webpack-dashboard 0.4, currently unable to select or copy text

**Comment by kenwheeler** [comment]
Sounds like holding down `fn` or `shift` while selecting might fix this. Can anyone confirm this works for them?

**Comment by JeremyPlease** [comment]
Holding down `fn` works for me on MacOS 10.12 using Terminal.

**Comment by ryan-roemer** [comment]
In iterm2 on my MacOS 10.12

- `option`: highlight full rows of text
- `option+command`: highlight a draggable box of text

In Terminal:

- `fn`:  highlight full rows of text
- `fn+option`: highlight a draggable box of text

I think best bet forward is probably just documenting this in a small PR.

/cc @kenwheeler

**Comment by carlospaelinck** [comment]
Added docs on how to copy-paste for different OS/Terminals.
