### ISSUE TITLE
How to temporary disable webpack-dashboard when just generate bundle files?

### ISSUE THREAD

**Issue by zhaozhiming** [FormidableLabs/webpack-dashboard#48]
Hi,
I use webpack-dashboard in my dev env and it work prefect. Something like this:  
```
webpack-dev-server --inline --config webpack.config.js
```
But I have a npm script to generate js and css bundle file, when run this script the terminal go to the dashboard and can't stop. The npm script like this:  
```
webpack --config webpack.config.js --progress
```

How could I temporary disable webpack-dashboard when I bundle my js and css files? Thanks.

**Comment by kenwheeler** [comment]
Can you try with this branch and let me know if this approach fixes your issue? https://github.com/FormidableLabs/webpack-dashboard/pull/50

**Comment by topheman** [comment]
@zhaozhiming this might help you: https://github.com/topheman/react-es6-redux/commit/a4ba7d7d84bd8931cef9d5bec972391b9b10fdf7 - you'll have all the configs to conditionally activate webpack-dashboard from your `webpack.config.js` file, based on an outside var (be it an env var, an argument or whatever ...).

**Comment by kenwheeler** [comment]
This should be fixed in the latest release

**Comment by zhaozhiming** [comment]
@kenwheeler OK. Thanks. 👍 

@topheman Good point, Thanks.
