### ISSUE TITLE
Minimal UI

### ISSUE THREAD

**Issue by igorbt** [FormidableLabs/webpack-dashboard#52]
It would be nice to have a minimal UI option or even a responsive layout. Currently, to be usable it should ocupy at least 50% of the screen height which for me is a lot because it is competing with code editor, browser and DevTools. I coudn't find an always visible place for it on my 2 monitors.

**Comment by kenwheeler** [comment]
This is a great idea. Let me play with some layouts and I'll see what i can come up with.

**Comment by kenwheeler** [comment]
Ideally I'll build it into #50 and you can pass a --minimal flag

**Comment by igorbt** [comment]
Wow! That's a pretty quick response! Thank you!

**Comment by kenwheeler** [comment]
Closing, minimal mode added in the latest release
