### ISSUE TITLE
spawn error on startup (Windows 7)

### ISSUE THREAD

**Issue by sparty02** [FormidableLabs/webpack-dashboard#57]
I totally understand if Windows isn't really supported yet, but thought I'd give you a heads up that I'm hitting an issue upon startup.

**With this run script:**
```js
"scripts": {
    "dev": "webpack-dashboard -- webpack-dev-server --config ./webpack.dev.js"
}
```

**And this in my webpack plugins:**
```js
plugins: [
    new DashboardPlugin()
]
```

**I get the following error:**
```bash
> webpack-dashboard -- webpack-dev-server --config ./webpack.dev.config.js

Error: spawn webpack-dev-server ENOENT
    at exports._errnoException (util.js:1007:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:160:18)
    at node.js:456:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev:app"
npm ERR! node v6.2.1
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
```

**Comment by kenwheeler** [comment]
Can you try the old way of hooking things up? Looks like from some initial research that spawn gets funny on windows. I gotta get a test env set up.

**Comment by sparty02** [comment]
Alrighty, yep, it does work great using the old way, e.g.

```js
var Dashboard = require('webpack-dashboard');
var DashboardPlugin = require('webpack-dashboard/plugin');
var dashboard = new Dashboard();
```
and
```js
new DashboardPlugin(dashboard.setData)
```

**Comment by kenwheeler** [comment]
Hey, for shits and giggles, can you install dev server globally and try? I might have to resolve to a local node_modules dir.

**Comment by sparty02** [comment]
> Hey, for shits and giggles, can you install dev server globally and try? I might have to resolve to a local node_modules dir.

Already tried that before reporting :wink:

**Comment by kenwheeler** [comment]
Do you have to prefix stuff with cmd on Windows?

**Comment by sparty02** [comment]
I'm actually using git bash

**Comment by sparty02** [comment]
> Do you have to prefix stuff with cmd on Windows?

FWIW, I just tried it in cmd.  Same error..... but what did you mean by "prefix stuff"?

**Comment by jing2si** [comment]
I have same error
windows 10

**Comment by jing2si** [comment]
**npm-debug-log**
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@2.15.0
3 info using node@v4.4.2
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info predev webpack-es6@1.0.0
6 info dev webpack-es6@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info webpack-es6@1.0.0 Failed to exec dev script
9 verbose stack Error: webpack-es6@1.0.0 dev: `webpack-dashboard -- webpack-dev-server --hot --inline --host 0.0.0.0`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid webpack-es6@1.0.0
11 verbose cwd F:\webpack-es6
12 error Windows_NT 10.0.10586
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
14 error node v4.4.2
15 error npm  v2.15.0
16 error code ELIFECYCLE
17 error webpack-es6@1.0.0 dev: `webpack-dashboard -- webpack-dev-server --hot --inline --host 0.0.0.0`
17 error Exit status 1
18 error Failed at the webpack-es6@1.0.0 dev script 'webpack-dashboard -- webpack-dev-server --hot --inline --host 0.0.0.0'.
18 error This is most likely a problem with the webpack-es6 package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     webpack-dashboard -- webpack-dev-server --hot --inline --host 0.0.0.0
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs webpack-es6
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls webpack-es6
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by kenwheeler** [comment]
Ok it looks like I'll have to spawn with https://www.npmjs.com/package/win-spawn . When I get this going, can you guys help test?

**Comment by sparty02** [comment]
> When I get this going, can you guys help test?

You bet

**Comment by sparty02** [comment]
@kenwheeler  FYI https://github.com/ForbesLindesay/win-spawn#deprecated-use-cross-spawn-or-cross-spawn-async-instead

**Comment by kenwheeler** [comment]
Cross spawn it is

**Comment by ryan-roemer** [comment]
You can also consider exec if amenable to arg combining yourself... It can be more Windows reliable...

**Comment by jing2si** [comment]
I have new problem now.
I can see dashboard but display nothing data.
