### ISSUE TITLE
Use without webpack-dev-server

### ISSUE THREAD

**Issue by SethTompkins** [FormidableLabs/webpack-dashboard#58]
I am trying to run the dashboard without using webpack-dev-server and I am getting incorrect output.

**Plugin:**
```
new DashboardPlugin({
		port: 3001,
		handler: dashboard.setData
	}),
```

**Command:**
`webpack-dashboard -- webpack --watch --devtool #eval-cheap-module-source-map`

**Output:**

<img width="1676" alt="screen shot 2016-08-17 at 11 00 46 pm" src="https://cloud.githubusercontent.com/assets/3925226/17760534/761400e6-64ce-11e6-95c6-3bfdd63965fe.png">

Is this only intended to be used with webpack-dev-server? I am using webpack to compile my js and sass on a php-based site so it is not very practical to use the dev-server.

Thank you for this awesome looking package :)

**Comment by kenwheeler** [comment]
Have you tried not passing any options to the DashboardPlugin constructor? When using the binary, it creates the dashboard instance for you, so you dont need to create an instance and pass the setData handler. Closing, let me know if this works out for you. If not, please reopen.

**Comment by SethTompkins** [comment]
This does work after removing all arguments - even having a port argument would cause it to fail.

Before the update, I noticed that error reports were properly syntax highlighted. With the new version it seems that they are non-colorized.

<img width="1241" alt="screen shot 2016-08-18 at 7 38 27 am" src="https://cloud.githubusercontent.com/assets/3925226/17772521/40a3aae4-6517-11e6-8962-f9e40254f327.png">

Seems like a pretty nitpicky thing, I was just curious if it was an intentional change or not.

**Comment by kenwheeler** [comment]
Arguments from dashboard or arguments from your webpack command? If you specify port you need to pass it with `-p` to the dashboard bin, and then as { port: yourport } to the plugin constructor.

**Comment by SethTompkins** [comment]
Ah, yea I was just passing the port # to the constructor in my webpack.config.js. I did not realize that it needed to be passed to the bin as well. In the docs it reads as an either/or kind of thing.
