### ISSUE TITLE
Add CI (Travis, Appveyor)

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/webpack-dashboard#6]
- [x] Travis CI (linux)
  - [x] Add matrix for all supported nodes.
- [x] AppVeyor (windows)
  - [x] Add matrix for all supported nodes.

... or something equivalent

**Comment by amilajack** [comment]
First there needs to be some build step or test we can run.

**Comment by raybooysen** [comment]
Teamcity too. :)

**Comment by nickytonline** [comment]
Jenkins too. :)

**Comment by parkerziegler** [comment]
Closed by #285 🎉
