### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by mistadikay** [FormidableLabs/webpack-dashboard#60]
Hey guys,

love your project, but while there are not too many versions have been released, maybe it would be a good idea to add a `changelog.md` right from the start and maintain it? Thanks

**Comment by kenwheeler** [comment]
I think i'm going to do that here https://github.com/FormidableLabs/webpack-dashboard/releases . If you want to PR a CHANGELOG.md and direct users there, I'll merge swiftly so you can get idea credit.

**Comment by mistadikay** [comment]
I just went and copied `redux-form` changelog — I think it fits the purpose greatly. Let me know if you need something changed there.
