### ISSUE TITLE
Quitting webpack-dashboard doesn't kill server

### ISSUE THREAD

**Issue by exogen** [FormidableLabs/webpack-dashboard#61]
When I launch `webpack-dashboard` the first time, everything works great. But when I quit by pressing `q`, then try to relaunch it, I get `Error: listen EADDRINUSE :::3000`. Browsing to my app confirms that the server `webpack-dashboard` launched the first time is still running, and can only be killed by tracking down the rogue process.

My setup, on OS X with `webpack-dashboard@0.1.1`:

In `package.json`:

```
"start:dev": "webpack-dashboard -- babel-node src/server.js"
```

In `src/server.js`:

```js
if (app.get('env') === 'development') {
  const config = require('../webpack.config.babel')
  const compiler = require('webpack')(config)
  const DashboardPlugin = require('webpack-dashboard/plugin')
  compiler.apply(new DashboardPlugin())
  app.use(require('webpack-dev-middleware')(compiler, {
    publicPath: config.output.publicPath,
    quiet: true
  }))
  app.use(require('webpack-hot-middleware')(compiler, {
    log: () => {}
  }))
}
```

**Comment by exogen** [comment]
After some experimentation, it looks like this works fine with `node src/server.js` (if I back off the Babel syntax) but fails for `babel-node src/server.js`. I'm on OS X, but the [Node docs](https://nodejs.org/api/child_process.html#child_process_child_kill_signal) say:

> Also note: on Linux, child processes of child processes will not be terminated when attempting to kill their parent. This is likely to happen when running a new process in a shell or with use of the shell option of ChildProcess [...]

which seems like it could apply here.

**Comment by exogen** [comment]
Some potential starting points for fixing the case where the process that `webpack-dashboard` launches spawns its own children:

* [forever-monitor](https://github.com/foreverjs/forever-monitor)
* [tree-kill](https://www.npmjs.com/package/tree-kill)

**Comment by ryan-roemer** [comment]
We use tree kill in builder and its pretty good - works on Mac, Linux and Windows (though not more esoteric platforms)

**Comment by kenwheeler** [comment]
@ryan-roemer for some reason, tree-kill isn't doing it. Spawning the command argument as detached and then killing its pid range seems to work. This might be the cause of shenanigans: https://github.com/babel/babel/blob/master/packages/babel-cli/src/babel-node.js#L77-L95

**Comment by lekhnath** [comment]
I am using nodemon@1.10.0 and having the same problem. But `q` and `Ctrl+c` both stops the server with vanilla node.

**Comment by bmv437** [comment]
can also confirm this bug, using the following command
`webpack-dashboard -- nodemon --exec babel-node bin/server`

**Comment by kenwheeler** [comment]
hey @lekhnath @bmv437 can you try with #63 ? That should do it.

**Comment by exogen** [comment]
@kenwheeler Working for me with both `babel-node` and `nodemon --exec babel-node`. Awesome job man.

@lekhnath @bmv437: You can test it like so: `npm install FormidableLabs/webpack-dashboard#fix-windows`

**Comment by bmv437** [comment]
@kenwheeler That works, thanks!

**Comment by snolflake** [comment]
FYI webpack-dev-server process in being left behind when the dashboard process is ended by closing a session on tmux (with <kbd>(prefix)</kbd> + <kbd>&</kbd>).

I have other watchers in that session that use spawned processes too but all of them are being terminated correctly and using [tmux-safekill](https://github.com/jlipps/tmux-safekill) has no effect, so I imagine it's just a matter of checking out which signal tmux send to end a session and handling it properly.

Let me know if I can be of any help. Thanks!

Versions info:
 - webpack-dashboard-0.2.1
 - webpack-dev-server-2.4.1
 - tmux-2.2
 - fedora 25
