### ISSUE TITLE
Issues with windows git bash

### ISSUE THREAD

**Issue by alisd23** [FormidableLabs/webpack-dashboard#62]
Hi, I tried using this on **Windows 7**, with **Git Bash** and I get no UI, just strange symbols moving across the screen:

Command: ```webpack-dashboard --node src/server/start-server.js```

![image](https://cloud.githubusercontent.com/assets/5804010/17767721/fa7fa696-6528-11e6-8078-89e6ac7155e9.png)

Is Git Bash supported, if not, any plans to support it?

**Comment by joyfulelement** [comment]
Had the exact same issue +1

**Comment by jedmao** [comment]
Same problem with Git Bash on Windows 10, as mentioned in https://github.com/FormidableLabs/webpack-dashboard/issues/43#issue-171540924

**Comment by kenwheeler** [comment]
First, you'll want to get the latest version. Second, set your term, as specified in #43 , and also in your scripts up there, you want a space between `--` and `node`. `--` is an end of options delimiter, so in current form it thinks you are setting a `--node` option.

**Comment by alisd23** [comment]
I tried setting the environment: ```TERM=windows-ansi```
and this command (properly typed):
```webpack-dashboard -- node src/server/start-server.js```

With this environment I get nothing instead of the random characters.

Also The issue with ```-- node``` was actually a typo sorry, even with the space it doesn't work.

**Comment by kenwheeler** [comment]
what happens when you run `node src/server/start-server.js`?

**Comment by alisd23** [comment]
Interestingly I get a ECONNREFUSED error, a port conflict I think.

![image](https://cloud.githubusercontent.com/assets/5804010/17811384/57c61136-661a-11e6-8938-b4fd20076d24.png)

Without webpack-dashboard I do not get the error

**Comment by kenwheeler** [comment]
Can i see how you're adding the DashboardPlugin? Is that port not open?

**Comment by alisd23** [comment]
```JavaScript
const webpackCompiler = webpack(webpackConfig);
webpackCompiler.apply(new DashboardPlugin());

const app = express();

// Webpack middleware
app.use(webpackDevMiddleware(webpackCompiler, {
   reload: true
}));
app.use(webpackHotMiddleware(webpackCompiler));
```


So that's all I'm doing, then using that webpackCompiler for the `dev` and `hot` middleware

**Comment by jedmao** [comment]
I'm still having this exact same issue on v0.1.4, both with and without the `TERM=windows-ansi` environment variable. I think this issue should be reopened.

**Comment by kenwheeler** [comment]
@jedmao can you open a new one and follow the issue template?
