### ISSUE TITLE
text color based on theme ?

### ISSUE THREAD

**Issue by lekhnath** [FormidableLabs/webpack-dashboard#68]
Unable to read text properly when terminal background color set to light (ie white). Specially when used with the minimal option `-m`. 
How does it sound to specify `-t dark|light` command line argument and based on those value use the appropriate text color by this tool. I am aware of the -c option and here I am talking about the dimmed text only. So that I am not forced to use dark theme in my terminal for using this super duper awesome cool tool.

Thankyou.
![webpack dashboard](https://cloud.githubusercontent.com/assets/4231691/17781072/7a287756-658d-11e6-84ff-def998f0e4e9.png)

**Comment by kenwheeler** [comment]
Thanks for the heads up, I have this fixed on a branch.

**Comment by kenwheeler** [comment]
This should be fixed in the latest release.
