### ISSUE TITLE
Incompatible with postcss-reporter

### ISSUE THREAD

**Issue by emattias** [FormidableLabs/webpack-dashboard#69]
This is what the output looks like when using [postcss-reporter](https://github.com/postcss/postcss-reporter)  😭 

<img width="1057" alt="screen shot 2016-08-18 at 18 05 04" src="https://cloud.githubusercontent.com/assets/351537/17781230/c81e2f4c-656e-11e6-8fec-a577a65ceb94.png">

This is my postcss setup in webpack.config.js:

```
  postcss: () => [
    postCssStyleLint,
    postCssImport({path: 'src'}),
    postCssCssNext({ browsers: 'last 2 versions' }),
    postCssReporter
  ],
```

**Comment by kenwheeler** [comment]
how do you have this set up?

**Comment by kenwheeler** [comment]
Are you using the approach detailed here: https://github.com/FormidableLabs/webpack-dashboard#packagejson-recommended , with the latest version?

**Comment by emattias** [comment]
This contains all the code I added to webpack.config.js for webpack-dashboard:

```js
import Dashboard from 'webpack-dashboard';
import DashboardPlugin from 'webpack-dashboard/plugin';
const dashboard = new Dashboard();

import common from './webpack.config.common'

const config = {
  ...common,

  devtool: 'source-map',

  output: {
    path: 'dist/',
    filename: 'bundle.js',
    publicPath: '/',
  },

  plugins: [
    ...common.plugins,
    new DashboardPlugin(dashboard.setData)
  ]
}

config.entry = ['react-hot-loader/patch', ...config.entry]

export default config
```

**Comment by kenwheeler** [comment]
Please instead set it up as described here https://github.com/FormidableLabs/webpack-dashboard#packagejson-recommended .

You don't need an instance of Dashboard inside your webpack config anymore. The binary in package.json handles that.

**Comment by emattias** [comment]
Great, now the output is inside of the log box but some coloring appears to be removed (yellow [stylelint] suffix)

<img width="1043" alt="screenshot at aug 18 19-41-24" src="https://cloud.githubusercontent.com/assets/351537/17784240/137e5900-657c-11e6-8779-a005a76d1a60.png">

**Comment by kenwheeler** [comment]
That'll be fixed in the next release

**Comment by emattias** [comment]
🎉

**Comment by kenwheeler** [comment]
You're all set
