### ISSUE TITLE
[Discuss] Support Legacy Node 0.10, 0.12 (?)

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/webpack-dashboard#7]
There's nothing in this project that needs es-next stuff (like say a React project). And we've already got one error from a user using old node ( #5 ).

Let's chat up perhaps making this ES5 / old node compatible? (I wouldn't advocate for babel transpilation for something as simple as this.)

**Comment by kenwheeler** [comment]
It looks like blessed supports >0.8 , and thats the only dependency, so we should be able to support old node. I just need to go through and remove the template literals and lets and it should be good to go.

**Comment by jdalton** [comment]
Just a heads up [Node v0.10 will be completely unsupported in just 50 days](https://twitter.com/feross/status/763548182416494593).

**Comment by jdalton** [comment]
Also `--harmony` is hax so shouldn't bother supporting that either.

**Comment by ide** [comment]
The way React Native addresses this (for one possible way to address this) is to have a small entry file written to run on old Node that checks your Node version and prints a banner message with instructions how to upgrade.

**Comment by ryan-roemer** [comment]
At this point, Node 0.10 support is pretty easy and straightforward with just writing the library being ES5. We will do a continued cost/benefit analysis of supporting Node 0.10 and 0.12 going forward with an eye towards eventual removal as either:

1. the hard constraints of our deps / devDeps evolve over time; and/or
2. is just becomes a reasonable pain to support 0.10 / 0.12

Right now, we're just basically converting an arrow function, so I'm going categorize the support cost as "low" 😉

**Comment by Aweary** [comment]
Looks like this was completed in https://github.com/FormidableLabs/webpack-dashboard/commit/9e5cf1313f6578db181b1f4479b182ea07bb098e, for reference.

**Comment by ryan-roemer** [comment]
Travis CI only checks

```yml
node_js:
  - "4"
  - "6"
  - "8"
```

Closing.
