### ISSUE TITLE
compatibility with babel --watch

### ISSUE THREAD

**Issue by benmonro** [FormidableLabs/webpack-dashboard#70]
I have a pre-build step which executes babel (and other commands) with a watch before starting my dev server.  As a result of this, the console logs from babel are messing up the dashboard (see the 3 screenshots below showing the progression). Is there a way to route the output of babel into the logs of webpack dashboard so that this doesn't happen?  I tried configuring this with the old approach and the new approach.  neither worked.

here's a snippet of my scripts in package.json:

``` json
    "predev": "npm run link && npm run build:ext:watch & npm run build -- --watch &",
    "build": "babel src --out-dir lib",
    "dev": "webpack-dashboard -- nodemon -d 1 lib/server.js --ignore 'assets.json'",
```

![image](https://cloud.githubusercontent.com/assets/399236/17783573/7c029e54-652d-11e6-8967-e51b73e08a57.png)

![image](https://cloud.githubusercontent.com/assets/399236/17783594/973c4224-652d-11e6-9cae-ef85dd9b2038.png)

![image](https://cloud.githubusercontent.com/assets/399236/17783612/a9344292-652d-11e6-885f-bfc0ca16cf26.png)

**Comment by kenwheeler** [comment]
I'm actually not sure how I could hook into that.

**Comment by benmonro** [comment]
ah bummer.  kind of a deal breaker.  :(

**Comment by kenwheeler** [comment]
Any ideas?

**Comment by benmonro** [comment]
a couple thoughts came to mind.  one would be to somehow pipe the output of the npm run build into your CLI... another (more hacky) would be to pipe npm run build into a file and have webpack-dashboard read from that.  those were the only 2 thoughts that came to mind.  not that they're very good but there they are.  :)

**Comment by ryan-roemer** [comment]
`webpack-dashboard` needs to be the first thing starting other processes. You could for instance, run babel in a separate terminal if I'm understanding things correctly to get rid of the logs, or potentially start things concurrently in the same terminal...
