### ISSUE TITLE
 When information is too long, the interface dislocation

### ISSUE THREAD

**Issue by aemoe** [FormidableLabs/webpack-dashboard#73]
When information is too long, the interface dislocation,look like below,hope fixed it,thx~ ~

![IMG](https://raw.githubusercontent.com/aemoe/Web-Isomorphism-Framework/master/README/872E2F91-4011-4D04-B158-2E4C896C0135.png)

**Comment by kenwheeler** [comment]
can I see how you have this set up?

**Comment by kenwheeler** [comment]
Closing pending more information

**Comment by usebaz** [comment]
I have a similar problem:

![Screen](http://storage7.static.itmages.com/i/16/1220/h_1482231063_6058684_53ecb72104.jpeg)

webpack.config.js:
```
const Dashboard = require('webpack-dashboard');
const DashboardPlugin = require('webpack-dashboard/plugin');
const dashboard = new Dashboard();
 
config.plugins.push(new DashboardPlugin(dashboard.setData));
```

Run webpack in gulp task:
```
const compiler = webpack(webpackConfig({
  needCompress: NEED_COMPRESS,
  isProductionBuild: IS_PRODUCTION_BUILD
}));
compiler.watch({
  aggregateTimeout: 300
}, webpackStat);
```
