### ISSUE TITLE
Colored output from express.js is all red.

### ISSUE THREAD

**Issue by jbreckel** [FormidableLabs/webpack-dashboard#78]
Expected: `DEBUG=* node index.js`
![screen shot 2016-08-19 at 15 43 17](https://cloud.githubusercontent.com/assets/9253219/17811608/c1b1f282-6623-11e6-81cf-b637cb7b0ef7.png)

Actual: `DEBUG=* webpack-dashboard node index.js`
![screen shot 2016-08-19 at 15 42 23](https://cloud.githubusercontent.com/assets/9253219/17811607/c19a3872-6623-11e6-832d-1f6604443b90.png)

====================================================================

###### Steps to reproduce the problem

1. use `express`
2. start server with setting the `DEBUG` environment variable: `DEBUG=* node index.js`
3. expect colorful output (screenshot 1) 

====================================================================

###### More Details

- What operating system are you on? 
    `Mac OS 10.11.6`

- What terminal application are you using? 
    `iTerm 3.0.5`

- What version of webpack-dashboard are you using? 
     `0.1.2`

- What is the output of running `echo $TERM`?
     `xterm-256color`

**Comment by kenwheeler** [comment]
Is there a reason that it's coming through via stderr? https://github.com/FormidableLabs/webpack-dashboard/blob/master/dashboard/index.js#L94

**Comment by kenwheeler** [comment]
I'm more concerned about the date string than the color, I can fix the color.

**Comment by jbreckel** [comment]
oh it seems like this is somehow the default in [debug](https://www.npmjs.com/package/debug)

**Comment by jbreckel** [comment]
and the timestamp comes also from debug:
> When stdout is not a TTY, Date#toUTCString() is used, making it more useful for logging the debug information as shown below: 
http://f.cl.ly/items/112H3i0e0o0P0a2Q2r11/Screenshot.png

**Comment by jbreckel** [comment]
and if I modify `debug` like they explain:
```
debug.log = console.info.bind(console);
```
the output is just white.
so the problem with the color seems to be, that the dashboard output is not a TTY.

Thanks for pointing me in the right direction.

**Comment by kenwheeler** [comment]
interesting. What about if you did something like: DEBUG_FD=1 to set output to stdout?

**Comment by jbreckel** [comment]
Thanks. 
It works as well and displays everything in white.
