### ISSUE TITLE
node: bad option --color

### ISSUE THREAD

**Issue by lekhnath** [FormidableLabs/webpack-dashboard#79]
Crashes the app if used with `nodemon`. I am using webpack-dashboard@0.1.2 

###### Screenshot 

![screenshot from 2016-08-19 20 07 28](https://cloud.githubusercontent.com/assets/4231691/17812859/9e3856e6-6648-11e6-9929-a9a06a34544c.png)

###### Steps to reproduce the problem

`webpack-dashboard -- nodemon ./bin/www`

**Comment by kenwheeler** [comment]
What terminal are you using?

**Comment by lekhnath** [comment]
Terminal: GNOME Terminal 3.6.1
Nodemon: 1.10.0

PS: Works perfectly with vanilla `node` though

**Comment by SEAPUNK** [comment]
I can confirm this issue, except this is for webpack-dev-server.

package.json script:

`node lifecycle-scripts/devel && webpack-dashboard -- webpack-dev-server --host 0.0.0.0 --config lifecycle-scripts/webpack-dev-config.js --content-base build/devel`

Terminal is `xfce4-terminal 0.6.3`

**Comment by SEAPUNK** [comment]
Could it be because of this line? https://github.com/FormidableLabs/webpack-dashboard/blob/master/bin/webpack-dashboard.js#L28

**Comment by kenwheeler** [comment]
Just pushed out 0.1.3, should fix it?

**Comment by lekhnath** [comment]
I think `args.push("--color");` is causing this #L28

**Comment by lekhnath** [comment]
Seems fixed for me :+1: @kenwheeler with 0.1.3

**Comment by kenwheeler** [comment]
@SEAPUNK does 0.1.3 work for you? @lekhnath did you install directly?

**Comment by lekhnath** [comment]
I did `npm i webpack-dashboard -D` it grabbed 0.1.4 @kenwheeler

**Comment by kenwheeler** [comment]
did 0.1.3 work for either of you?

**Comment by SEAPUNK** [comment]
I'm checking, hold on.

**Comment by SEAPUNK** [comment]
Yep, it works! Thank you!

**Comment by SEAPUNK** [comment]
Although... the modules and assets dialogues don't show anything.

![](http://i.imgur.com/W5vDX49.png)

**Comment by kenwheeler** [comment]
what about 0.1.4?

**Comment by SEAPUNK** [comment]
That was 0.1.4.

**Comment by kenwheeler** [comment]
how about 0.1.3 then

**Comment by SEAPUNK** [comment]
See above. I edited my comment.

**Comment by SEAPUNK** [comment]
Looks like my remaining issue is related to #72.
