### ISSUE TITLE
Non-watch Webpack instances hang when dashboard is running

### ISSUE THREAD

**Issue by aequasi** [FormidableLabs/webpack-dashboard#88]
My workflow has a watch, and then a non-watch webpack process. The non-watch one runs any time I push or pull from git. When i have the watch process running, with the dashboard, the non-watch process hangs until i kill it or the dashboard.

**Comment by kenwheeler** [comment]
Can you resubmit this bug using the info template and show me some info I can use to debug?

**Comment by aequasi** [comment]
https://github.com/FormidableLabs/webpack-dashboard/issues/96
