### ISSUE TITLE
Win7 - webpack-dashboard doesn't seem to be finding webpack-dev-server

### ISSUE THREAD

**Issue by gitgrimbo** [FormidableLabs/webpack-dashboard#91]
> Please provide a description of the bug / issue, and provide the details below:

`webpack-dashboard` doesn't seem to be finding/executing `webpack-dev-server`.

On running `npm start` there is no disk/CPU activity (which is generally evidence that webpack is starting).  I see a dashboard, but it has no data in it.

````
  "scripts": {
    "start": "webpack-dashboard -- webpack-dev-server --inline --hot --compress --content-base ./",
...
  },
````

====================================================================

###### If the issue is visual, please provide screenshots here

I have added code to `webpack-dashboard.js`

````js
console.log(command);
````
and

````js
child.stderr.on("data", function (data) {
  console.log("ERR-DATA"+data);
````

and this prints out:

````
d:\dev\git_repos\harviewer-react>node_modules\.bin\webpack-dashboard -- webpack-dev-server --colors --no-info
webpack-dev-server
ERR-DATAchild_process.js:61
  p.open(fd);
    ^

Error: EBADF: bad file descriptor, uv_pipe_open
    at Error (native)
    at Object.exports._forkChild (child_process.js:61:5)
    at Object.setupChannel (internal/process.js:239:8)
    at startup (bootstrap_node.js:61:16)
    at bootstrap_node.js:467:3
````

====================================================================

###### Steps to reproduce the problem

Install as per the instructions, `npm install webpack-dashboard --save-dev` and then modify `npm start` script in `package.json` (as above).

====================================================================

###### More Details

- What operating system are you on? **Windows 7**
- What terminal application are you using?  **cmd.exe**
- What version of webpack-dashboard are you using? **0.1.6**
- What is the output of running `echo $TERM`? **n/a**

**Comment by kenwheeler** [comment]
Lets continue this in #83
