### ISSUE TITLE
Only the log shows up and no other section shows up 

### ISSUE THREAD

**Issue by killerdejavu** [FormidableLabs/webpack-dashboard#94]
> Please provide a description of the bug / issue, and provide the details below:

Only the log shows up and nothing else
====================================================================

###### If the issue is visual, please provide screenshots here
![screenshot 2016-08-22 11 26 13](https://cloud.githubusercontent.com/assets/3146856/17844862/5479ed0c-685b-11e6-8549-b0f9d0c0f585.png)

====================================================================

###### Steps to reproduce the problem
Just did the steps told to start. And ended up with this
====================================================================

###### Please provide a gist of relevant files

1. package.json 
```
"scripts": {
    "dev": "webpack-dashboard -p 3002 -- ./node_modules/.bin/webpack-dev-server --config webpack.dev.babel.js --hot --progress --colors"
  }
```
2. webpack.config.js
```
var DashboardPlugin = require('webpack-dashboard/plugin');
    plugins: [
        new HtmlWebpackPlugin(generateHtmlConfig({
            chunks: ['appbundle', 'vendors'],
            app_name: 'appbundle'
        })),
        new webpack.optimize.CommonsChunkPlugin({
            name: 'vendors',
            minChunks: module => (/node_modules/).test(module.resource)
        }),
        new WriteFilePlugin(),
        new DashboardPlugin({ port:3002 })
    ],
```
====================================================================

###### More Details

- What operating system are you on? - OSX
- What terminal application are you using? - iTerm2
- What version of webpack-dashboard are you using? 0.16
- What is the output of running `echo $TERM`? - xterm-256color

**Comment by danielverejan** [comment]
Try setting the webpack "quiet" to true. You should not have those logs in dashboard.

**Comment by killerdejavu** [comment]
@danielverejan Still no difference. And I can't see anything in other boxes as well.

**Comment by CreepGin** [comment]
Showing of the logs is fine. @killerdejavu You can try 2 things:

1) Remove `--progress --colors`.
2) Put `new DashboardPlugin({ port:3002 })` to the first position of the array.

**Comment by kenwheeler** [comment]
try that ^

**Comment by mattybow** [comment]
@killerdejavu was just having the same issue, I removed the port specification from `new DashboardPlugin()` and the other sections populated.
```
new WebpackDevServer(webpack(config), {
  publicPath: config.output.publicPath,
  hot: true,
  quiet: false,
  historyApiFallback: true,
  stats: {
    colors: true
  }
}).listen(PORT, HOST, err => {
  if(err){
    console.log(err);
  }
  console.log(`Listening on ${HOST}:${PORT}`);
})
```
```
"scripts": {
    "start": "source env.sh && HOST='localhost' PORT=5001 webpack-dashboard -- node server",
}
```

**Comment by killerdejavu** [comment]
@mattybow Thanks for the tip! Worked for me.

**Comment by cristian-sima** [comment]
> Please provide a description of the bug / issue, and provide the details below:

# Only the log shows up and nothing else 

====================================================================

###### If the issue is visual, please provide screenshots here
This is what I am seeing in PowerShell

![image](https://cloud.githubusercontent.com/assets/12199042/17882133/36990c9c-6913-11e6-99a2-429a0c19aeb2.png)

In the Command:

![image](https://cloud.githubusercontent.com/assets/12199042/17882197/8d7f5a84-6913-11e6-984a-8414fc953e03.png)

====================================================================

###### Steps to reproduce the problem

====================================================================

###### Please provide a gist of relevant files

1. package.json (specifically the script you are using to start the dashboard)
```
webpack-dashboard -c -p 3002 -- node server.js
```
2. webpack.config.js
```
plugins: [
  new webpack.DefinePlugin({
      'process.env': {
        'NODE_ENV': JSON.stringify('development')
      }
    }),
    new DashboardPlugin()
]
```
3. server.js (Your express based dev server, if applicable)
```js
var webpack = require('webpack');
var WebpackDevServer = require('webpack-dev-server');
var config = require('./webpack.config');

new WebpackDevServer(webpack(config), {
  publicPath: config.output.publicPath,
  hot: true,
  inline: true,
  headers: { 'Access-Control-Allow-Origin': '*' },
  stats: { colors: true },
  historyApiFallback: true,
  proxy: {
    '/': {
      target: 'http://127.0.0.1:3000',
    },
    '/x*': {
      target: 'http://127.0.0.1:3000',
    },
    '/client*': {
      target: 'http://127.0.0.1:8080',
    },
    '/static*': {
      target: 'http://127.0.0.1:8080',
      rewrite: function(req) {
        console.log('req.url',req.url);
        req.url =  "/server" +  req.url;
      }
    },
    '/api*': {
      target: "http://127.0.0.1:3000"
    }
  }
}).listen(8080, '127.0.0.1', function (err, result) {
  if (err) {
    return console.log(err);
  }

  console.log('The dev server is listening at http://127.0.0.1:8080/');
});

```

====================================================================

###### More Details

- What operating system are you on? 
![image](https://cloud.githubusercontent.com/assets/12199042/17885082/340e011a-6924-11e6-82e6-5fc2a5443a69.png)

- What terminal application are you using? `PowerShell` and `cmd.exe`
- What version of webpack-dashboard are you using? `0.1.7`
- What is the output of running `echo $TERM`? `nothing`

**Comment by cristian-sima** [comment]
@mattybow I've tried your solution, but I am getting this: 

![image](https://cloud.githubusercontent.com/assets/12199042/17885581/77ae31b8-6926-11e6-9dfa-012e39115c2c.png)

**Comment by caisah** [comment]
I have the same problem (only log shows up):
`package.json`:
```json
  "scripts": {
     "start-dev-server": "./node_modules/.bin/webpack-dashboard -- ./node_modules/.bin/webpack-dev-server",
```

`webpackfile.js`:
```js
  devServer: {
    contentBase: PATH.output,
    port: 8000,
    quiet: false,
    open: true,
    inline: true,
  },
    plugins: [
      new webpack.HotModuleReplacementPlugin(),
      new DashboardPlugin(),
    ],
```

OSX
webpack@2.1.0-beta.21
webpack-dev-server@1.15.0
webpack-dashboard@0.1.8
xterm-256color

**Comment by phanimahesh** [comment]
Same issue. Only logs show up. Suggested workarounds have no effect
