### ISSUE TITLE
Visual Studio Task Runner console throwing error

### ISSUE THREAD

**Issue by wahabshah** [FormidableLabs/webpack-dashboard#97]
I am using dashboard from command line and it works as expected :) so great work.:+1: 
But when running it from **Visual Studio Task Runner** console, it is throwing error.

``` javascript
if (!this.program.isAlt) return;
                   ^
TypeError: Cannot read property 'isAlt' of undefined
```

I have installed an NPM Task Runner extension, which makes it easy to double click an npm script to execute it in VS console. Plus such scripts can be bound to actions like opening VS.
I know it might not be a bug but is it possible to make it work on VS console as well, because it will make it convenient.
# 
###### Here is the screen shot of the error

![image](https://cloud.githubusercontent.com/assets/8818025/17880449/3b0f4f38-68fb-11e6-8b9e-2be1e862b8ca.png)
# 
###### Please provide a gist of relevant files

**package.json** (specifically the script you are using to start the dashboard)

``` javascript
"scripts": {
    "start": "node server.js",
  },
```

**webpack.config.js**

``` javascript
var Dashboard = require('webpack-dashboard');
var DashboardPlugin = require('webpack-dashboard/plugin');
var dashboard = new Dashboard();
 plugins: [
                 new DashboardPlugin(dashboard.setData)
    ],  
```

**server.js** (Your express based dev server, if applicable)

``` javascript
/* eslint-disable no-var, strict */
var webpack = require('webpack');
var WebpackDevServer = require('webpack-dev-server');
var config = require('./webpack.config');

new WebpackDevServer(webpack(config), {
    stats: { colors: true },
    proxy: {
        "*": "http://localhost:7479" // <- backend
    },
    publicPath: config.output.publicPath,
    quiet: true, // lets WebpackDashboard do its thing
  hot: true,
  historyApiFallback: true
}).listen(5000, 'localhost', function (err) {
    if (err) {
      console.log(err);
    }
    console.log('Listening at localhost:5000');
  });
```
# 
###### More Details
- What operating system are you on?
  I am using Windows
- What terminal application are you using?
  Visual Studio Task Runner console
- What version of webpack-dashboard are you using?
  0.1.7
- What is the output of running `echo $TERM`?

**Comment by danielverejan** [comment]
First make sure that Visual Studio is using the global installed version of npm not it's local.
![mfpro](https://cloud.githubusercontent.com/assets/7072732/17999283/4b6a6e2a-6b81-11e6-8e46-c44860c4e586.png)
Move $(PATH) to the top.

**Comment by hyndsite** [comment]
@danielverejan 's solution worked for me.

**Comment by ryan-roemer** [comment]
Looks like this was solved. If not, please update to `^1.0.1`, see if the issue persists, and if not open a minimal respository + install / reproduction steps and we'll dive in (and most of us use VS Code...). Thanks!
